// Generated by Odroe. Do not edit.

import 'package:odroe/router.dart';
import 'routes/route.dart' as root_definition;
import 'routes/404.html/route.dart' as route404_html_definition;
import 'routes/docs/route.dart' as docs_definition;
import 'routes/docs/[...slug]/route.dart' as docs_rest_slug_definition;

final _routeDocsRestSlug = docs_rest_slug_definition.route.compiled(
  path: "**:slug",
  terminal: true,
  params: PathParams<docs_rest_slug_definition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _routeDocs = docs_definition.route.compiled(
  path: "docs",
  terminal: true,
  children: <RouteNode>[_routeDocsRestSlug],
);

final _routeRoute404Html = route404_html_definition.route.compiled(
  path: "404.html",
  terminal: true,
);

final _routeRoot = root_definition.route.compiled(
  path: "/",
  terminal: true,
  children: <RouteNode>[_routeRoute404Html, _routeDocs],
);

/// Compiled client route tree.
final List<RouteNode> routeTree = <RouteNode>[_routeRoot];

/// Typed references to filesystem routes.
const routes = AppRoutes();

/// Typed references below filesystem route "/".
final class AppRoutes {
  /// Creates a stateless route reference group.
  const AppRoutes();

  /// Routes below filesystem route "/404.html".
  final AppRoute404HtmlRoutes route404Html = const AppRoute404HtmlRoutes();

  /// Routes below filesystem route "/docs".
  final AppDocsRoutes docs = const AppDocsRoutes();
}

/// Typed references below filesystem route "/404.html".
final class AppRoute404HtmlRoutes {
  /// Creates a stateless route reference group.
  const AppRoute404HtmlRoutes();
}

/// Typed references below filesystem route "/docs".
final class AppDocsRoutes {
  /// Creates a stateless route reference group.
  const AppDocsRoutes();

  /// Routes below filesystem route "/docs/[...slug]".
  final AppDocsRestSlugRoutes restSlug = const AppDocsRestSlugRoutes();
}

/// Typed references below filesystem route "/docs/[...slug]".
final class AppDocsRestSlugRoutes {
  /// Creates a stateless route reference group.
  const AppDocsRestSlugRoutes();
}
