// Generated by Odroe. Do not edit.

import 'package:odroe/router.dart';
import 'package:odroe/server.dart';
import 'package:odroe/document.dart';
import "routes/route.dart" as root_definition;
import "routes/404.html/route.dart" as route404_html_definition;
import "routes/docs/server.dart" as docs_server;
import "routes/docs/[...slug]/route.dart" as docs_rest_slug_definition;
import "routes/docs/[...slug]/server.dart" as docs_rest_slug_server;

final _serverRouteDocsRestSlug = docs_rest_slug_server.route.compiled(
  path: "**:slug",
  terminal: true,
  params: PathParams<docs_rest_slug_definition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _serverRouteDocs = docs_server.route.compiled(
  path: "docs",
  terminal: true,
  children: <RouteNode>[_serverRouteDocsRestSlug],
);

final _serverRouteRoute404Html = route404_html_definition.route.compiled(
  path: "404.html",
  terminal: true,
);

final _serverRouteRoot = root_definition.route.compiled(
  path: "/",
  terminal: true,
  children: <RouteNode>[_serverRouteRoute404Html, _serverRouteDocs],
);

/// Compiled server route tree.
final List<RouteNode> serverRouteTree = <RouteNode>[_serverRouteRoot];

/// Server functions addressable by generated clients.
final serverFunctions = <String, ServerFunctionBinding>{};

/// Creates the application server from generated routes.
Server createServer({
  Iterable<Module> Function()? modules,
  InvocationModuleFactory? invocationModules,
  Iterable<Middleware> middleware = const <Middleware>[],
  Serializer? serializer,
  Renderer? renderer,
  ServerErrorHandler? onError,
  ServerCloseHandler? onClose,
  int maxFunctionPayload = Server.defaultMaxFunctionPayload,
  int maxFunctionResponseFrameBytes =
      Server.defaultMaxFunctionResponseFrameBytes,
}) => Server(
  routes: serverRouteTree,
  functions: serverFunctions,
  modules: modules,
  invocationModules: invocationModules,
  flutterRoutes: <RouteNode>[],
  middleware: middleware,
  serializer: serializer,
  onError: onError,
  onClose: onClose,
  maxFunctionPayload: maxFunctionPayload,
  maxFunctionResponseFrameBytes: maxFunctionResponseFrameBytes,
  renderer:
      renderer ??
      const DocumentRenderer(
        flutterBootstrap: '/flutter_bootstrap.js',
        baseHref: '/',
      ).call,
);
