// ignore_for_file: public_member_api_docs

import 'dart:convert';
import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import 'model.dart';
import 'server_functions.dart';

final class RouteGenerator {
  const RouteGenerator({
    required this.projectRoot,
    required this.outputFile,
    required this.serverOutputFile,
  });

  final Directory projectRoot;
  final File outputFile;
  final File serverOutputFile;

  String generateClient(List<RouteNode> nodes) {
    final hasFunctions = nodes.any((node) => node.functions.isNotEmpty);
    final clientImports = _clientFunctionImports(nodes);
    final buffer = StringBuffer()
      ..writeln('// Generated by Odroe. Do not edit.')
      ..writeln('// ignore_for_file: type=lint')
      ..writeln()
      ..writeln("import 'package:odroe/route.dart';");
    if (hasFunctions) {
      buffer.writeln("import 'package:odroe/rpc.dart';");
    }
    for (final entry in clientImports.imports) {
      buffer.writeln(
        entry.alias == null
            ? "import '${entry.uri}';"
            : "import '${entry.uri}' as ${entry.alias};",
      );
    }
    for (final node in nodes) {
      for (final entry in node.imports(outputFile.parent.path)) {
        buffer.writeln("import '${entry.uri}' as ${entry.alias};");
      }
    }
    buffer.writeln();

    for (final node in nodes.reversed) {
      _writeCompiledRoute(buffer, node);
    }
    buffer
      ..writeln('final List<RouteNode> routeTree = <RouteNode>[_routeRoot];')
      ..writeln()
      ..writeln('const routes = AppRoutes();')
      ..writeln();
    for (final node in nodes) {
      _writeFacade(buffer, node, clientImports.prefixes);
    }
    return DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    ).format(buffer.toString());
  }

  String generateServer(RouteNode root, List<RouteNode> nodes) {
    final typeImports = _clientFunctionImports(nodes, target: serverOutputFile);
    final decoderSources = <String>[
      for (final node in nodes)
        for (final function in node.functions)
          if (wireDecoder(
                _clientFunctionType(
                  node,
                  function.inputType,
                  typeImports.prefixes,
                ),
                'value',
              ) !=
              null)
            _clientFunctionType(node, function.inputType, typeImports.prefixes),
    ];
    final buffer = StringBuffer()
      ..writeln('// Generated by Odroe. Do not edit.')
      ..writeln('// ignore_for_file: type=lint')
      ..writeln()
      ..writeln("import 'package:odroe/route.dart';")
      ..writeln("import 'package:odroe/server.dart';");
    for (final entry in typeImports.imports) {
      final used = entry.alias == null
          ? decoderSources.any(
              (source) => RegExp(
                r'\b(?:Uint8List|Int8List|Uint16List|Int16List|Uint32List|Int32List|Uint64List|Int64List|Float32List|Float64List|ByteData|ByteBuffer)\b',
              ).hasMatch(source),
            )
          : decoderSources.any((source) => source.contains('${entry.alias}.'));
      if (!used) continue;
      buffer.writeln(
        entry.alias == null
            ? "import '${entry.uri}';"
            : "import '${entry.uri}' as ${entry.alias};",
      );
    }
    for (final node in nodes) {
      if (node.routeFile case final file?) {
        buffer.writeln(
          "import '${_importUri(file, serverOutputFile.parent.path)}' "
          'as ${node.routeAlias};',
        );
      }
      if (node.serverFile case final file?) {
        buffer.writeln(
          "import '${_importUri(file, serverOutputFile.parent.path)}' "
          'as ${node.serverAlias};',
        );
      }
    }
    buffer.writeln();
    for (final node in nodes.reversed) {
      _writeCompiledServerRoute(buffer, node);
    }
    buffer
      ..writeln(
        'final List<RouteNode> serverRouteTree = '
        '<RouteNode>[${root.serverVariable}];',
      )
      ..writeln()
      ..writeln('final serverFunctions = <String, ServerFunctionBinding>{');
    for (final node in nodes) {
      for (final function in node.functions) {
        final id = _functionId(node, function);
        final input = _clientFunctionType(
          node,
          function.inputType,
          typeImports.prefixes,
        );
        final decoder = wireDecoder(input, 'value');
        buffer.writeln(
          '  ${jsonEncode(id)}: ServerFunctionBinding('
          '${node.serverAlias}.${function.name},'
          '${decoder == null ? '' : ' decodeInput: (value) => $decoder,'}'
          '),',
        );
      }
    }
    buffer
      ..writeln('};')
      ..writeln()
      ..writeln('OdroeServer createServer({')
      ..writeln('  Iterable<Middleware> middleware = const <Middleware>[],')
      ..writeln('  Serializer? serializer,')
      ..writeln('  Renderer? renderer,')
      ..writeln('}) => OdroeServer(')
      ..writeln('  routes: serverRouteTree,')
      ..writeln('  functions: serverFunctions,')
      ..writeln('  middleware: middleware,')
      ..writeln('  serializer: serializer,')
      ..writeln('  renderer: renderer,')
      ..writeln(');');
    return DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    ).format(buffer.toString());
  }

  void _writeCompiledServerRoute(StringBuffer buffer, RouteNode node) {
    final base = node.serverFile != null
        ? '${node.serverAlias}.route'
        : node.routeFile != null
        ? '${node.routeAlias}.route'
        : 'AppRoute<NoParams, NoSearch, NoData>()';
    buffer
      ..writeln('final ${node.serverVariable} = $base.compiled(')
      ..writeln('  path: ${jsonEncode(node.path)},')
      ..writeln('  terminal: ${node.isPageTerminal || node.serverTerminal},')
      ..writeln('  hasFlutterPage: ${node.pageFile != null},');
    final contract = node.contract;
    if (contract?.paramsSchema ?? false) {
      _writeParamsCodec(buffer, node, contract!.params!);
    }
    if (contract?.searchSchema ?? false) {
      _writeSearchCodec(buffer, node, contract!.search!);
    }
    if (node.children.isNotEmpty) {
      buffer
        ..writeln('  children: <RouteNode>[')
        ..writeAll(
          node.children.map((child) => '    ${child.serverVariable},\n'),
        )
        ..writeln('  ],');
    }
    buffer
      ..writeln(');')
      ..writeln();
  }

  void _writeCompiledRoute(StringBuffer buffer, RouteNode node) {
    final base = node.shellFile != null
        ? node.pageFile == null
              ? '${node.shellAlias}.route'
              : '${node.shellAlias}.route.withPage(${node.pageAlias}.route)'
        : node.pageFile != null
        ? '${node.pageAlias}.route'
        : node.routeFile != null
        ? '${node.routeAlias}.route'
        : 'AppRoute<NoParams, NoSearch, NoData>()';
    buffer
      ..writeln('final ${node.variable} = $base.compiled(')
      ..writeln('  path: ${jsonEncode(node.path)},')
      ..writeln('  terminal: ${node.isPageTerminal},');
    final contract = node.contract;
    if (contract?.paramsSchema ?? false) {
      _writeParamsCodec(buffer, node, contract!.params!);
    }
    if (contract?.searchSchema ?? false) {
      _writeSearchCodec(buffer, node, contract!.search!);
    }
    if (node.children.isNotEmpty) {
      buffer
        ..writeln('  children: <RouteNode>[')
        ..writeAll(node.children.map((child) => '    ${child.variable},\n'))
        ..writeln('  ],');
    }
    buffer
      ..writeln(');')
      ..writeln();
  }

  void _writeParamsCodec(
    StringBuffer buffer,
    RouteNode node,
    RecordContract record,
  ) {
    buffer
      ..writeln('  params: PathParams<${node.routeAlias}.Params>.codec(')
      ..writeln('    decode: (input) => (');
    for (final field in record.fields) {
      buffer.writeln('      ${field.name}: ${_pathDecode(field)},');
    }
    buffer
      ..writeln('    ),')
      ..writeln('    encode: (value, output) {');
    for (final field in record.fields) {
      buffer.writeln('      ${_pathEncode(field)}');
    }
    buffer
      ..writeln('    },')
      ..writeln('  ),');
  }

  void _writeSearchCodec(
    StringBuffer buffer,
    RouteNode node,
    RecordContract record,
  ) {
    final defaults = '${node.routeAlias}.route.search!.defaults';
    buffer
      ..writeln('  search: SearchParams<${node.routeAlias}.Search>.codec(')
      ..writeln(
        '    keys: const <String>{${record.fields.map((field) => jsonEncode(field.name)).join(', ')}},',
      )
      ..writeln('    defaults: $defaults,')
      ..writeln('    invalid: ${node.routeAlias}.route.search!.invalid,')
      ..writeln('    decode: (input) => (');
    for (final field in record.fields) {
      buffer.writeln('      ${field.name}: ${_searchDecode(field, defaults)},');
    }
    buffer
      ..writeln('    ),')
      ..writeln('    encode: (value, output) {');
    for (final field in record.fields) {
      buffer.writeln('      ${_searchEncode(field, defaults)}');
    }
    buffer
      ..writeln('    },')
      ..writeln('  ),');
  }

  void _writeFacade(
    StringBuffer buffer,
    RouteNode node,
    Map<String, String> typePrefixes,
  ) {
    buffer
      ..writeln('final class ${node.className} {')
      ..writeln('  const ${node.className}();');
    for (final child in node.children) {
      buffer
        ..writeln()
        ..writeln(
          '  final ${child.className} ${child.memberName} = '
          'const ${child.className}();',
        );
    }
    for (final function in node.functions) {
      final input = _clientFunctionType(node, function.inputType, typePrefixes);
      final output = function.streamType == null
          ? _clientFunctionType(node, function.outputType, typePrefixes)
          : _clientFunctionType(node, function.streamType!, typePrefixes);
      final reference = function.streamType == null
          ? 'ServerFunctionRef<$input, $output>'
          : 'ServerStreamFunctionRef<$input, $output>';
      final decoder = wireDecoder(output, 'value');
      buffer
        ..writeln()
        ..writeln(
          '  $reference get ${function.name} => '
          '${decoder == null ? 'const ' : ''}$reference(',
        )
        ..writeln('    id: ${jsonEncode(_functionId(node, function))},')
        ..writeln('    method: ${function.method},');
      if (decoder != null) {
        buffer.writeln('    decodeOutput: (value) => $decoder,');
      }
      buffer.writeln('  );');
    }
    if (node.pageFile != null) {
      final params = node.allParams;
      final searchOwners = node.lineage
          .where((owner) => owner.contract?.search != null)
          .toList(growable: false);
      buffer.writeln();
      if (params.isEmpty && searchOwners.isEmpty) {
        buffer.writeln('  Destination to() {');
      } else {
        buffer.writeln('  Destination to({');
      }
      if (params.isNotEmpty) {
        buffer.writeln('    required ${_recordType(params)} params,');
      }
      for (final owner in searchOwners) {
        buffer.writeln(
          '    ${owner.routeAlias}.Search? '
          '${owner.searchArgumentName(target: node)},',
        );
      }
      if (params.isNotEmpty || searchOwners.isNotEmpty) {
        buffer.writeln('  }) {');
      }
      final lineage = node.lineage;
      for (var index = 0; index < lineage.length; index++) {
        final ancestor = lineage[index];
        final local = ancestor.contract?.params?.fields ?? const <RouteField>[];
        final arguments = <String>[];
        if (local.isNotEmpty) {
          arguments.add(
            'params: '
            '(${local.map((field) => '${field.name}: params.${field.name}').join(', ')},)',
          );
        }
        if (ancestor.contract?.search != null) {
          arguments.add('search: ${ancestor.searchArgumentName(target: node)}');
        }
        final ref = '${ancestor.variable}.ref(${arguments.join(', ')})';
        if (index == 0) {
          buffer.write('    return $ref');
        } else {
          buffer.write('.then($ref)');
        }
      }
      buffer
        ..writeln('.destination;')
        ..writeln('  }');
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  String _recordType(List<RouteField> fields) =>
      '({${fields.map((field) => '${_qualifiedType(field)} ${field.name}').join(', ')}})';

  String _qualifiedType(RouteField field) {
    final type = field.type;
    final bare = type.endsWith('?') ? type.substring(0, type.length - 1) : type;
    final suffix = type.endsWith('?') ? '?' : '';
    if (const <String>{'String', 'int', 'double', 'bool'}.contains(bare)) {
      return '$bare$suffix';
    }
    if (bare == 'List<String>') return 'List<String>$suffix';
    if (const <String>{
      'num',
      'BigInt',
      'DateTime',
      'Duration',
      'Uri',
      'Object',
      'dynamic',
      'Never',
    }.contains(bare)) {
      return '$bare$suffix';
    }
    return '${field.owner!.routeAlias}.$bare$suffix';
  }

  _ClientFunctionImports _clientFunctionImports(
    List<RouteNode> nodes, {
    File? target,
  }) {
    final imports = <_GeneratedImport>[];
    final prefixes = <String, String>{};
    final seen = <String>{};
    var needsTypedData = false;
    for (final node in nodes) {
      for (final function in node.functions) {
        final sources = <String>[
          function.inputType,
          function.outputType,
          if (function.streamType != null) function.streamType!,
        ];
        needsTypedData |= sources.any(
          (source) => RegExp(
            r'\b(?:Uint8List|Int8List|Uint16List|Int16List|Uint32List|Int32List|Uint64List|Int64List|Float32List|Float64List|ByteData|ByteBuffer)\b',
          ).hasMatch(source),
        );
        for (final entry in node.serverImports) {
          final prefix = entry.prefix;
          if (prefix == null ||
              !sources.any((source) => source.contains('$prefix.'))) {
            continue;
          }
          final key = '${node.key}:$prefix';
          if (entry.uri == 'package:odroe/server.dart') {
            prefixes[key] = '';
            continue;
          }
          final serverFile = node.serverFile!;
          final imported = _resolveImport(serverFile, entry.uri);
          if (node.routeFile != null &&
              imported != null &&
              p.equals(imported, node.routeFile!.absolute.path)) {
            prefixes[key] = node.routeAlias;
            continue;
          }
          final alias =
              '_${_lowerIdentifier(node.key)}${_upperIdentifier(prefix)}Type';
          prefixes[key] = alias;
          final uri = _forwardImportUri(
            serverFile,
            entry.uri,
            target ?? outputFile,
          );
          if (seen.add('$uri|$alias')) {
            imports.add(_GeneratedImport(uri: uri, alias: alias));
          }
        }
      }
    }
    if (needsTypedData && seen.add('dart:typed_data|')) {
      imports.add(const _GeneratedImport(uri: 'dart:typed_data'));
    }
    return _ClientFunctionImports(imports: imports, prefixes: prefixes);
  }

  String _clientFunctionType(
    RouteNode node,
    String source,
    Map<String, String> prefixes,
  ) {
    var result = source;
    for (final entry in node.serverImports) {
      final prefix = entry.prefix;
      if (prefix == null) continue;
      final replacement = prefixes['${node.key}:$prefix'];
      if (replacement == null) continue;
      result = result.replaceAll(
        '$prefix.',
        replacement.isEmpty ? '' : '$replacement.',
      );
    }
    return result;
  }

  String _functionId(RouteNode node, ServerFunctionDeclaration function) {
    final path = _relative(node.serverFile!.path).split(p.separator).join('/');
    return '$path#${function.name}';
  }

  String? _resolveImport(File from, String uri) {
    final parsed = Uri.tryParse(uri);
    if (parsed != null && parsed.hasScheme) return null;
    return p.normalize(p.join(from.parent.path, uri));
  }

  String _forwardImportUri(File from, String uri, File target) {
    final resolved = _resolveImport(from, uri);
    if (resolved == null) return uri;
    return p
        .relative(resolved, from: target.parent.path)
        .split(p.separator)
        .join('/');
  }

  String _importUri(File file, String from) =>
      p.relative(file.path, from: from).split(p.separator).join('/');

  String _lowerIdentifier(String value) {
    final clean = value.replaceAll(RegExp(r'[^A-Za-z0-9]'), '');
    return clean.isEmpty
        ? 'route'
        : '${clean[0].toLowerCase()}${clean.substring(1)}';
  }

  String _upperIdentifier(String value) {
    final clean = value.replaceAll(RegExp(r'[^A-Za-z0-9]'), '');
    return clean.isEmpty
        ? 'Import'
        : '${clean[0].toUpperCase()}${clean.substring(1)}';
  }

  String _pathDecode(RouteField field) => switch (field.type) {
    'String' => "input.requiredString('${field.name}')",
    'int' => "input.requiredInt('${field.name}')",
    'double' => "input.requiredDouble('${field.name}')",
    'bool' => "input.requiredBool('${field.name}')",
    'List<String>' => "input.segments('${field.name}')",
    _ => throw StateError('Unsupported generated path type ${field.type}.'),
  };

  String _pathEncode(RouteField field) => switch (field.type) {
    'String' => "output.string('${field.name}', value.${field.name});",
    'int' => "output.integer('${field.name}', value.${field.name});",
    'double' => "output.decimal('${field.name}', value.${field.name});",
    'bool' => "output.boolean('${field.name}', value.${field.name});",
    'List<String>' => "output.segments('${field.name}', value.${field.name});",
    _ => throw StateError('Unsupported generated path type ${field.type}.'),
  };

  String _searchDecode(RouteField field, String defaults) {
    final type = field.type.replaceAll('?', '');
    final read = switch (type) {
      'String' => "input.string('${field.name}')",
      'int' => "input.integer('${field.name}')",
      'double' => "input.decimal('${field.name}')",
      'bool' => "input.boolean('${field.name}')",
      'List<String>' => "input.strings('${field.name}')",
      _ => throw StateError('Unsupported generated search type ${field.type}.'),
    };
    if (type == 'List<String>') {
      return "input.strings('${field.name}', "
          'fallback: $defaults.${field.name})';
    }
    return '$read ?? $defaults.${field.name}';
  }

  String _searchEncode(RouteField field, String defaults) {
    final type = field.type.replaceAll('?', '');
    final method = switch (type) {
      'String' => 'string',
      'int' => 'integer',
      'double' => 'decimal',
      'bool' => 'boolean',
      'List<String>' => 'strings',
      _ => throw StateError('Unsupported generated search type ${field.type}.'),
    };
    return "output.$method('${field.name}', value.${field.name}, "
        'omitIf: $defaults.${field.name});';
  }

  String _relative(String path) => p.relative(path, from: projectRoot.path);
}

final class _ClientFunctionImports {
  const _ClientFunctionImports({required this.imports, required this.prefixes});

  final List<_GeneratedImport> imports;
  final Map<String, String> prefixes;
}

final class _GeneratedImport {
  const _GeneratedImport({required this.uri, this.alias});

  final String uri;
  final String? alias;
}
