import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import 'dart_source.dart';
import 'model.dart';
import 'wire_codec.dart';

/// Emits typed client and server route trees from scanned nodes.
final class RouteGenerator {
  /// Creates a generator for client and server targets.
  const RouteGenerator({
    required this.projectRoot,
    required this.outputFile,
    required this.serverOutputFile,
  });

  /// Application package root.
  final Directory projectRoot;

  /// Generated client target.
  final File outputFile;

  /// Generated server target.
  final File serverOutputFile;

  /// Generates the Flutter/client-safe route tree and navigation facade.
  String generateClient(List<RouteNode> nodes) {
    final hasFunctions = nodes.any((node) => node.functions.isNotEmpty);
    final clientImports = _clientFunctionImports(nodes);
    final buffer = StringBuffer()
      ..writeln('// Generated by Odroe. Do not edit.')
      ..writeln()
      ..writeln("import 'package:odroe/router.dart';");
    if (hasFunctions) {
      buffer.writeln("import 'package:odroe/rpc.dart';");
    }
    for (final entry in clientImports.imports) {
      buffer.writeln(
        entry.alias == null
            ? 'import ${dartStringLiteral(entry.uri)};'
            : 'import ${dartStringLiteral(entry.uri)} as ${entry.alias};',
      );
    }
    for (final node in nodes) {
      for (final entry in node.imports(outputFile.parent.path)) {
        buffer.writeln(
          'import ${dartStringLiteral(entry.uri)} as ${entry.alias};',
        );
      }
    }
    buffer.writeln();

    for (final node in nodes.reversed) {
      if (!node.emitsRuntimeRoute) continue;
      _writeCompiledRoute(buffer, node);
    }
    final root = nodes.first;
    final runtimeRoots = root.emitsRuntimeRoute
        ? <RouteNode>[root]
        : root.runtimeChildren.toList(growable: false);
    buffer
      ..writeln('/// Compiled client route tree.')
      ..writeln(
        'final List<RouteNode> routeTree = <RouteNode>['
        '${runtimeRoots.map((node) => node.variable).join(', ')}];',
      )
      ..writeln()
      ..writeln('/// Typed references to filesystem routes.')
      ..writeln('const routes = AppRoutes();')
      ..writeln();
    for (final node in nodes) {
      _writeFacade(buffer, node, clientImports.prefixes);
    }
    return DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    ).format(buffer.toString());
  }

  /// Generates the server route tree and server-function manifest.
  String generateServer(RouteNode root, List<RouteNode> nodes) {
    final hasRenderer = nodes.any(
      (node) =>
          node.pageFile != null || (node.contract?.declaresDocument ?? false),
    );
    final typeImports = _clientFunctionImports(nodes, target: serverOutputFile);
    final codecSources = <String>[];
    for (final node in nodes) {
      String qualify(String source) =>
          _clientFunctionType(node, source, typeImports.prefixes);
      for (final function in node.functions) {
        codecSources.addAll(
          _decoderTypeSources(function.inputWireShape).map(qualify),
        );
        codecSources.addAll(
          _encoderTypeSources(
            function.outputWireShape,
            cast: true,
          ).map(qualify),
        );
      }
    }
    final buffer = StringBuffer()
      ..writeln('// Generated by Odroe. Do not edit.')
      ..writeln()
      ..writeln("import 'package:odroe/odroe.dart';")
      ..writeln("import 'package:odroe/router.dart';")
      ..writeln("import 'package:odroe/server.dart';");
    if (hasRenderer) {
      buffer.writeln("import 'package:odroe/document.dart';");
    }
    for (final entry in typeImports.imports) {
      final used = entry.alias == null
          ? codecSources.any(_usesUnprefixedTypedData)
          : codecSources.any(
              (source) => _usesImportPrefix(source, entry.alias!),
            );
      if (!used) continue;
      buffer.writeln(
        entry.alias == null
            ? 'import ${dartStringLiteral(entry.uri)};'
            : 'import ${dartStringLiteral(entry.uri)} as ${entry.alias};',
      );
    }
    for (final node in nodes) {
      final contract = node.contract;
      final needsRouteTypes =
          (contract?.paramsSchema ?? false) ||
          (contract?.searchSchema ?? false);
      if (node.routeFile case final file?) {
        if (node.serverFile == null || needsRouteTypes) {
          buffer.writeln(
            'import ${dartStringLiteral(_importUri(file, serverOutputFile.parent.path))} '
            'as ${node.routeAlias};',
          );
        }
      }
      if (node.serverFile case final file?) {
        buffer.writeln(
          'import ${dartStringLiteral(_importUri(file, serverOutputFile.parent.path))} '
          'as ${node.serverAlias};',
        );
      }
    }
    buffer.writeln();
    for (final node in nodes.reversed) {
      if (!node.emitsRuntimeRoute) continue;
      _writeCompiledServerRoute(buffer, node);
    }
    final runtimeRoots = root.emitsRuntimeRoute
        ? <RouteNode>[root]
        : root.runtimeChildren.toList(growable: false);
    buffer
      ..writeln('/// Compiled server route tree.')
      ..writeln(
        'final List<RouteNode> serverRouteTree = '
        '<RouteNode>['
        '${runtimeRoots.map((node) => node.serverVariable).join(', ')}];',
      )
      ..writeln()
      ..writeln('/// Server functions addressable by generated clients.')
      ..writeln('final serverFunctions = <String, ServerFunctionBinding>{');
    for (final node in nodes) {
      for (final function in node.functions) {
        String qualify(String source) =>
            _clientFunctionType(node, source, typeImports.prefixes);
        final decoder = wireDecoder(
          function.inputWireShape,
          'value',
          qualify: qualify,
        );
        final encoder = wireEncoder(
          function.outputWireShape,
          'value',
          qualify: qualify,
          cast: true,
        );
        buffer.writeln(
          '  ${dartStringLiteral(function.wireId)}: ServerFunctionBinding('
          '${node.serverAlias}.${function.name},'
          '${decoder == null ? '' : ' decodeInput: (value) => $decoder,'}'
          '${encoder == null ? '' : ' encodeOutput: (value) => $encoder,'}'
          '),',
        );
      }
    }
    final flutterRoutes = nodes
        .where((node) => node.pageFile != null)
        .map((node) => node.serverVariable)
        .join(', ');
    buffer
      ..writeln('};')
      ..writeln()
      ..writeln('/// Creates the application server from generated routes.')
      ..writeln('Server createServer({')
      ..writeln('  Iterable<Module> Function()? modules,')
      ..writeln('  InvocationModuleFactory? invocationModules,')
      ..writeln('  Iterable<Middleware> middleware = const <Middleware>[],')
      ..writeln('  Serializer? serializer,')
      ..writeln('  Renderer? renderer,')
      ..writeln('  ServerErrorHandler? onError,')
      ..writeln('  ServerCloseHandler? onClose,')
      ..writeln('  int maxFunctionPayload = Server.defaultMaxFunctionPayload,')
      ..writeln(
        '  int maxFunctionResponseFrameBytes = '
        'Server.defaultMaxFunctionResponseFrameBytes,',
      )
      ..writeln('}) => Server(')
      ..writeln('  routes: serverRouteTree,')
      ..writeln('  functions: serverFunctions,')
      ..writeln('  modules: modules,')
      ..writeln('  invocationModules: invocationModules,')
      ..writeln('  flutterRoutes: <RouteNode>[$flutterRoutes],')
      ..writeln('  middleware: middleware,')
      ..writeln('  serializer: serializer,')
      ..writeln('  onError: onError,')
      ..writeln('  onClose: onClose,')
      ..writeln('  maxFunctionPayload: maxFunctionPayload,')
      ..writeln(
        '  maxFunctionResponseFrameBytes: maxFunctionResponseFrameBytes,',
      )
      ..writeln(
        hasRenderer
            ? '  renderer: renderer ?? const DocumentRenderer('
                  "flutterBootstrap: '/flutter_bootstrap.js', "
                  "baseHref: '/',).call,"
            : '  renderer: renderer,',
      )
      ..writeln(');');
    return DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    ).format(buffer.toString());
  }

  void _writeCompiledServerRoute(StringBuffer buffer, RouteNode node) {
    final base = node.serverFile != null
        ? '${node.serverAlias}.route'
        : '${node.routeAlias}.route';
    buffer
      ..writeln('final ${node.serverVariable} = $base.compiled(')
      ..writeln('  path: ${dartStringLiteral(node.runtimePath)},')
      ..writeln('  terminal: ${node.isPageTerminal || node.serverTerminal},');
    final contract = node.contract;
    if (contract?.paramsSchema ?? false) {
      _writeParamsCodec(buffer, node, contract!.params!);
    }
    if (contract?.searchSchema ?? false) {
      _writeSearchCodec(buffer, node, contract!.search!);
    }
    final runtimeChildren = node.runtimeChildren.toList(growable: false);
    if (runtimeChildren.isNotEmpty) {
      buffer
        ..writeln('  children: <RouteNode>[')
        ..writeAll(
          runtimeChildren.map((child) => '    ${child.serverVariable},\n'),
        )
        ..writeln('  ],');
    }
    buffer
      ..writeln(');')
      ..writeln();
  }

  void _writeCompiledRoute(StringBuffer buffer, RouteNode node) {
    final base = node.shellFile != null
        ? node.pageFile == null
              ? '${node.shellAlias}.route'
              : '${node.shellAlias}.route.withPage(${node.pageAlias}.route)'
        : node.pageFile != null
        ? '${node.pageAlias}.route'
        : '${node.routeAlias}.route';
    buffer
      ..writeln('final ${node.variable} = $base.compiled(')
      ..writeln('  path: ${dartStringLiteral(node.runtimePath)},')
      ..writeln('  terminal: ${node.isPageTerminal},');
    final contract = node.contract;
    if (contract?.paramsSchema ?? false) {
      _writeParamsCodec(buffer, node, contract!.params!);
    }
    if (contract?.searchSchema ?? false) {
      _writeSearchCodec(buffer, node, contract!.search!);
    }
    final runtimeChildren = node.runtimeChildren.toList(growable: false);
    if (runtimeChildren.isNotEmpty) {
      buffer
        ..writeln('  children: <RouteNode>[')
        ..writeAll(runtimeChildren.map((child) => '    ${child.variable},\n'))
        ..writeln('  ],');
    }
    buffer
      ..writeln(');')
      ..writeln();
  }

  void _writeParamsCodec(
    StringBuffer buffer,
    RouteNode node,
    RecordContract record,
  ) {
    buffer
      ..writeln('  params: PathParams<${node.routeAlias}.Params>.codec(')
      ..writeln('    decode: (input) => (');
    for (final field in record.fields) {
      buffer.writeln('      ${field.name}: ${_pathDecode(field)},');
    }
    buffer
      ..writeln('    ),')
      ..writeln('    encode: (value, output) {');
    for (final field in record.fields) {
      buffer.writeln('      ${_pathEncode(field)}');
    }
    buffer
      ..writeln('    },')
      ..writeln('  ),');
  }

  void _writeSearchCodec(
    StringBuffer buffer,
    RouteNode node,
    RecordContract record,
  ) {
    final defaults = '${node.routeAlias}.route.search!.defaults';
    buffer
      ..writeln('  search: SearchParams<${node.routeAlias}.Search>.codec(')
      ..writeln(
        '    keys: const <String>{${record.fields.map((field) => dartStringLiteral(field.name)).join(', ')}},',
      )
      ..writeln('    defaults: $defaults,')
      ..writeln('    invalid: ${node.routeAlias}.route.search!.invalid,')
      ..writeln('    decode: (input) => (');
    for (final field in record.fields) {
      buffer.writeln('      ${field.name}: ${_searchDecode(field, defaults)},');
    }
    buffer
      ..writeln('    ),')
      ..writeln('    encode: (value, output) {');
    for (final field in record.fields) {
      buffer.writeln('      ${_searchEncode(field, defaults)}');
    }
    buffer
      ..writeln('    },')
      ..writeln('  ),');
  }

  void _writeFacade(
    StringBuffer buffer,
    RouteNode node,
    Map<String, String> typePrefixes,
  ) {
    buffer
      ..writeln(
        '/// Typed references below filesystem route '
        '${dartStringLiteral(_routeLabel(node))}.',
      )
      ..writeln('final class ${node.className} {')
      ..writeln('  /// Creates a stateless route reference group.')
      ..writeln('  const ${node.className}();');
    for (final child in node.children) {
      buffer
        ..writeln()
        ..writeln(
          '  /// Routes below filesystem route '
          '${dartStringLiteral(_routeLabel(child))}.',
        )
        ..writeln(
          '  final ${child.className} ${child.memberName} = '
          'const ${child.className}();',
        );
    }
    for (final function in node.functions) {
      final input = _clientFunctionType(node, function.inputType, typePrefixes);
      final output = function.streamType == null
          ? _clientFunctionType(node, function.outputType, typePrefixes)
          : _clientFunctionType(node, function.streamType!, typePrefixes);
      final reference = function.streamType == null
          ? 'ServerFunctionRef<$input, $output>'
          : 'ServerStreamFunctionRef<$input, $output>';
      String qualify(String source) =>
          _clientFunctionType(node, source, typePrefixes);
      final encoder = wireEncoder(
        function.inputWireShape,
        'value',
        qualify: qualify,
      );
      final decoder = wireDecoder(
        function.outputWireShape,
        'value',
        qualify: qualify,
      );
      buffer.writeln();
      final encoderName = '_encode${function.name}';
      final decoderName = '_decode${function.name}';
      if (encoder != null) {
        buffer
          ..writeln('  static Object? $encoderName($input value) => $encoder;')
          ..writeln();
      }
      if (decoder != null) {
        buffer
          ..writeln('  static $output $decoderName(Object? value) => $decoder;')
          ..writeln();
      }
      buffer
        ..writeln('  /// Calls `${function.name}` on the application server.')
        ..writeln(
          '  $reference get ${function.name} => '
          'const $reference(',
        );
      buffer
        ..writeln('    id: ${dartStringLiteral(function.wireId)},')
        ..writeln('    method: ${function.method},');
      if (encoder != null) {
        buffer.writeln('    encodeInput: $encoderName,');
      }
      if (decoder != null) {
        buffer.writeln('    decodeOutput: $decoderName,');
      }
      buffer.writeln('  );');
    }
    if (node.pageFile != null) {
      final params = node.allParams;
      final searchOwners = node.lineage
          .where((owner) => owner.contract?.search != null)
          .toList(growable: false);
      buffer
        ..writeln()
        ..writeln('  /// Builds a destination for this route.');
      if (params.isEmpty && searchOwners.isEmpty) {
        buffer.writeln('  Destination to() {');
      } else {
        buffer.writeln('  Destination to({');
      }
      if (params.isNotEmpty) {
        buffer.writeln('    required ${_recordType(params)} params,');
      }
      for (final owner in searchOwners) {
        buffer.writeln(
          '    ${owner.routeAlias}.Search? '
          '${owner.searchArgumentName(target: node)},',
        );
      }
      if (params.isNotEmpty || searchOwners.isNotEmpty) {
        buffer.writeln('  }) {');
      }
      final lineage = node.runtimeLineage;
      for (var index = 0; index < lineage.length; index++) {
        final ancestor = lineage[index];
        final local = ancestor.contract?.params?.fields ?? const <RouteField>[];
        final arguments = <String>[];
        if (local.isNotEmpty) {
          arguments.add(
            'params: '
            '(${local.map((field) => '${field.name}: params.${field.name}').join(', ')},)',
          );
        }
        if (ancestor.contract?.search != null) {
          arguments.add('search: ${ancestor.searchArgumentName(target: node)}');
        }
        final ref = '${ancestor.variable}.ref(${arguments.join(', ')})';
        if (index == 0) {
          buffer.write('    return $ref');
        } else {
          buffer.write('.then($ref)');
        }
      }
      buffer
        ..writeln('.destination;')
        ..writeln('  }');
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  String _recordType(List<RouteField> fields) =>
      '({${fields.map((field) => '${_qualifiedType(field)} ${field.name}').join(', ')}})';

  String _routeLabel(RouteNode node) {
    return node.segments.isEmpty ? '/' : '/${node.segments.join('/')}';
  }

  String _qualifiedType(RouteField field) {
    final type = field.type;
    final bare = type.endsWith('?') ? type.substring(0, type.length - 1) : type;
    final suffix = type.endsWith('?') ? '?' : '';
    if (const <String>{'String', 'int', 'double', 'bool'}.contains(bare)) {
      return '$bare$suffix';
    }
    if (bare == 'List<String>') return 'List<String>$suffix';
    if (const <String>{
      'num',
      'BigInt',
      'DateTime',
      'Duration',
      'Uri',
      'Object',
      'dynamic',
      'Never',
    }.contains(bare)) {
      return '$bare$suffix';
    }
    return '${field.owner!.routeAlias}.$bare$suffix';
  }

  _ClientFunctionImports _clientFunctionImports(
    List<RouteNode> nodes, {
    File? target,
  }) {
    final imports = <_GeneratedImport>[];
    final prefixes = <String, String>{};
    final seen = <String>{};
    final aliasOwners = <String, String>{};
    final uriAliases = <String, String>{};
    var needsTypedData = false;
    for (final node in nodes) {
      for (final function in node.functions) {
        final sources = <String>[
          function.inputType,
          function.streamType ?? function.outputType,
        ];
        final codecTypes = target == null
            ? <String>[
                ..._encoderTypeSources(function.inputWireShape),
                ..._decoderTypeSources(function.outputWireShape),
              ]
            : <String>[
                ..._decoderTypeSources(function.inputWireShape),
                ..._encoderTypeSources(function.outputWireShape, cast: true),
              ];
        needsTypedData |= <String>[
          ...sources,
          ...codecTypes,
        ].any(_usesUnprefixedTypedData);
        for (final entry in node.serverImports) {
          final prefix = entry.prefix;
          if (prefix == null ||
              !sources.any((source) => _usesImportPrefix(source, prefix))) {
            continue;
          }
          final key = '${node.key}:$prefix';
          if (_isServerOnlyOdroeImport(entry.uri)) {
            prefixes[key] = '';
            continue;
          }
          final serverFile = node.serverFile!;
          final uri = _forwardImportUri(
            serverFile,
            entry.uri,
            target ?? outputFile,
          );
          final existingAlias = uriAliases[uri];
          if (existingAlias != null) {
            prefixes[key] = existingAlias;
            continue;
          }
          final aliasBase =
              '${_snakeIdentifier(node.key)}_'
              '${_snakeIdentifier(prefix)}_type';
          var alias = aliasBase;
          var suffix = 2;
          while (aliasOwners[alias] != null && aliasOwners[alias] != key) {
            alias = '${aliasBase}_${suffix++}';
          }
          aliasOwners[alias] = key;
          uriAliases[uri] = alias;
          prefixes[key] = alias;
          if (seen.add('$uri|$alias')) {
            imports.add(_GeneratedImport(uri: uri, alias: alias));
          }
        }
      }
    }
    if (needsTypedData && seen.add('dart:typed_data|')) {
      imports.add(const _GeneratedImport(uri: 'dart:typed_data'));
    }
    return _ClientFunctionImports(imports: imports, prefixes: prefixes);
  }

  String _clientFunctionType(
    RouteNode node,
    String source,
    Map<String, String> prefixes,
  ) {
    var result = source;
    for (final entry in node.serverImports) {
      final prefix = entry.prefix;
      if (prefix == null) continue;
      final replacement = prefixes['${node.key}:$prefix'];
      if (replacement == null) continue;
      result = _replaceImportPrefix(result, prefix, replacement);
    }
    return result;
  }

  String? _resolveImport(File from, String uri) {
    final parsed = Uri.tryParse(uri);
    if (parsed != null && parsed.hasScheme) return null;
    return p.normalize(p.join(from.parent.path, uri));
  }

  String _forwardImportUri(File from, String uri, File target) {
    final resolved = _resolveImport(from, uri);
    if (resolved == null) return uri;
    return p
        .relative(resolved, from: target.parent.path)
        .split(p.separator)
        .join('/');
  }

  String _importUri(File file, String from) =>
      p.relative(file.path, from: from).split(p.separator).join('/');

  String _snakeIdentifier(String value) {
    final identifier = value
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (match) => '${match.group(1)}_${match.group(2)}',
        )
        .replaceAll(RegExp(r'[^A-Za-z0-9]+'), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '')
        .toLowerCase();
    return identifier.isEmpty ? 'import' : identifier;
  }

  String _pathDecode(RouteField field) => switch (field.type) {
    'String' => "input.requiredString('${field.name}')",
    'int' => "input.requiredInt('${field.name}')",
    'double' => "input.requiredDouble('${field.name}')",
    'bool' => "input.requiredBool('${field.name}')",
    'List<String>' => "input.segments('${field.name}')",
    _ => throw StateError('Unsupported generated path type ${field.type}.'),
  };

  String _pathEncode(RouteField field) => switch (field.type) {
    'String' => "output.string('${field.name}', value.${field.name});",
    'int' => "output.integer('${field.name}', value.${field.name});",
    'double' => "output.decimal('${field.name}', value.${field.name});",
    'bool' => "output.boolean('${field.name}', value.${field.name});",
    'List<String>' => "output.segments('${field.name}', value.${field.name});",
    _ => throw StateError('Unsupported generated path type ${field.type}.'),
  };

  String _searchDecode(RouteField field, String defaults) {
    final type = field.type.replaceAll('?', '');
    final read = switch (type) {
      'String' => "input.string('${field.name}')",
      'int' => "input.integer('${field.name}')",
      'double' => "input.decimal('${field.name}')",
      'bool' => "input.boolean('${field.name}')",
      'List<String>' => "input.strings('${field.name}')",
      _ => throw StateError('Unsupported generated search type ${field.type}.'),
    };
    if (type == 'List<String>') {
      return "input.strings('${field.name}', "
          'fallback: $defaults.${field.name})';
    }
    return '$read ?? $defaults.${field.name}';
  }

  String _searchEncode(RouteField field, String defaults) {
    final type = field.type.replaceAll('?', '');
    final method = switch (type) {
      'String' => 'string',
      'int' => 'integer',
      'double' => 'decimal',
      'bool' => 'boolean',
      'List<String>' => 'strings',
      _ => throw StateError('Unsupported generated search type ${field.type}.'),
    };
    return "output.$method('${field.name}', value.${field.name}, "
        'omitIf: $defaults.${field.name});';
  }
}

Iterable<String> _decoderTypeSources(WireShape shape) sync* {
  if (shape is WireValueShape) return;
  yield* _nestedDecoderTypeSources(shape);
}

Iterable<String> _nestedDecoderTypeSources(WireShape shape) sync* {
  switch (shape) {
    case WireValueShape(:final source) when source != 'dynamic':
      yield source;
    case WireCollectionShape(kind: WireCollectionKind.map, value: final value):
      yield value.source;
      yield* _nestedDecoderTypeSources(value);
    case WireCollectionShape(:final value):
      yield* _nestedDecoderTypeSources(value);
    case WireRecordShape(:final fields):
      for (final field in fields) {
        yield* _nestedDecoderTypeSources(field.shape);
      }
    case WireValueShape():
  }
}

Iterable<String> _encoderTypeSources(
  WireShape shape, {
  bool cast = false,
}) sync* {
  if (!_containsWireRecord(shape)) return;
  if (cast) yield shape.source;
  yield* _nestedEncoderTypeSources(shape);
}

Iterable<String> _nestedEncoderTypeSources(WireShape shape) sync* {
  if (shape is! WireValueShape && shape.nullable) yield shape.source;
  switch (shape) {
    case WireRecordShape(:final fields):
      for (final field in fields) {
        yield* _nestedEncoderTypeSources(field.shape);
      }
    case WireCollectionShape(:final value) when _containsWireRecord(value):
      yield* _nestedEncoderTypeSources(value);
    case WireCollectionShape() || WireValueShape():
  }
}

bool _containsWireRecord(WireShape shape) => switch (shape) {
  WireRecordShape() => true,
  WireCollectionShape(:final value) => _containsWireRecord(value),
  WireValueShape() => false,
};

bool _usesImportPrefix(String source, String prefix) =>
    _importPrefixPattern(prefix).hasMatch(source);

String _replaceImportPrefix(String source, String prefix, String replacement) =>
    source.replaceAllMapped(
      _importPrefixPattern(prefix),
      (match) =>
          '${match.group(1)}${replacement.isEmpty ? '' : '$replacement.'}',
    );

RegExp _importPrefixPattern(String prefix) =>
    RegExp('(^|[^A-Za-z0-9_\$])${RegExp.escape(prefix)}\\.');

bool _usesUnprefixedTypedData(String source) => RegExp(
  r'(^|[^A-Za-z0-9_$.])(?:Uint8List|Int8List|Uint16List|Int16List|Int32List|Uint32List|Int64List|Uint64List|Float32List|Float64List|ByteData|ByteBuffer)\b',
).hasMatch(source);

bool _isServerOnlyOdroeImport(String uri) => const <String>{
  'package:odroe/server.dart',
  'package:odroe/server_fetch.dart',
  'package:odroe/server_io.dart',
}.contains(uri);

final class _ClientFunctionImports {
  const _ClientFunctionImports({required this.imports, required this.prefixes});

  final List<_GeneratedImport> imports;
  final Map<String, String> prefixes;
}

final class _GeneratedImport {
  const _GeneratedImport({required this.uri, this.alias});

  final String uri;
  final String? alias;
}
