import 'dart:convert';
import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import '../atomic_write.dart';
import 'full_stack_starter.dart';
import 'project.dart';

const _generatedHeader = '// Generated by Odroe. Do not edit.';

final _formatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);

/// Initializes one empty Flutter application with an Odroe product starter.
bool initializeProject(
  CliProject project,
  StringSink out,
  StringSink err, {
  bool fullStack = false,
}) {
  _validateFlutterApplication(project);
  final odroeLibrary = _validateOdroeResolution(project);
  final sources = fullStack
      ? fullStackStarterSources(
          packageName: project.packageName,
          sharedSources: _readFullStackSources(odroeLibrary),
        )
      : <String, String>{
          'lib/main.dart': _mainSource,
          'lib/routes/route.dart': _routeSource,
          'lib/routes/page.dart': _pageSource,
        };
  final files = <String, File>{
    for (final path in sources.keys)
      path: File(p.join(project.root.path, path)),
  };
  final routeFile = files['lib/routes/route.dart']!;
  final pageFile = files['lib/routes/page.dart']!;
  final routeServerFile = File(
    p.join(project.compiler.routesDirectory.path, 'server.dart'),
  );
  final gitIgnore = File(p.join(project.root.path, '.gitignore'));
  final trackedFiles = <File>{
    ...files.values,
    if (fullStack) gitIgnore,
    project.compiler.outputFile,
    project.compiler.serverOutputFile,
    project.bootstrap,
  }.toList(growable: false);

  final conflicts = <String>{};
  for (final file in trackedFiles) {
    _validateTargetPath(project.root, file, conflicts);
  }
  for (final entry in files.entries) {
    final expected = sources[entry.key]!;
    if (entry.key.endsWith('.dart')) {
      final allowed = <String>[expected];
      if (entry.key == 'lib/main.dart') {
        allowed.addAll(<String>[_flutterEmptyMainSource, _mainSource]);
      } else if (fullStack && entry.key == 'lib/routes/route.dart') {
        allowed.add(_routeSource);
      } else if (fullStack && entry.key == 'lib/routes/page.dart') {
        allowed.add(_pageSource);
      }
      _validateSource(
        entry.value,
        allowed,
        conflicts,
        allowBlank: entry.key == 'lib/main.dart',
      );
    } else {
      _validateTextSource(entry.value, expected, conflicts);
    }
  }
  _findUnexpectedDartSources(
    project,
    allowed: <String>{
      for (final entry in files.entries)
        if (entry.key.endsWith('.dart')) p.normalize(entry.value.absolute.path),
      p.normalize(project.compiler.outputFile.absolute.path),
      p.normalize(project.compiler.serverOutputFile.absolute.path),
    },
    conflicts: conflicts,
  );

  final basicRoutesExist =
      _matches(routeFile, _routeSource) && _matches(pageFile, _pageSource);
  final fullStackRoutesExist =
      fullStack &&
      _matches(routeFile, sources['lib/routes/route.dart']!) &&
      _matches(pageFile, sources['lib/routes/page.dart']!) &&
      _matches(routeServerFile, sources['lib/routes/server.dart']!);
  final starterRoutesExist = fullStack
      ? fullStackRoutesExist ||
            (basicRoutesExist && !routeServerFile.existsSync())
      : basicRoutesExist;
  final compiled = starterRoutesExist ? project.compiler.compile() : null;
  if (compiled != null && compiled.hasErrors) {
    conflicts.add(project.compiler.routesDirectory.path);
  }
  _validateGeneratedFile(
    project.compiler.outputFile,
    starterRoutesExist: starterRoutesExist,
    expected: compiled?.source,
    conflicts: conflicts,
  );
  _validateGeneratedFile(
    project.compiler.serverOutputFile,
    starterRoutesExist: starterRoutesExist,
    expected: compiled?.serverSource,
    conflicts: conflicts,
  );
  _validateGeneratedFile(
    project.bootstrap,
    starterRoutesExist: starterRoutesExist,
    expected: project.bootstrapIsCurrent
        ? project.bootstrap.readAsStringSync()
        : null,
    conflicts: conflicts,
  );
  if (conflicts.isNotEmpty) {
    final paths = conflicts.toList()..sort();
    throw FileSystemException(
      'odroe init requires an empty Flutter application and will not '
      'overwrite existing source:\n${paths.map((path) => '  $path').join('\n')}\n'
      'Start with `flutter create --empty`, or move the custom files first.',
    );
  }

  final wasCurrent =
      files.entries.every(
        (entry) => _hasExactContents(entry.value, sources[entry.key]!),
      ) &&
      (!fullStack || _hasGitIgnoreEntries(gitIgnore)) &&
      (fullStack ? fullStackRoutesExist : basicRoutesExist) &&
      project.compiler.outputFile.existsSync() &&
      project.compiler.outputFile.readAsStringSync() == compiled!.source &&
      project.compiler.serverOutputFile.existsSync() &&
      project.compiler.serverOutputFile.readAsStringSync() ==
          compiled.serverSource &&
      project.bootstrapIsCurrent;
  final snapshots = <File, List<int>?>{
    for (final file in trackedFiles)
      file: file.existsSync() ? file.readAsBytesSync() : null,
  };
  final directories = _snapshotDirectories(project.root, trackedFiles);
  var keepChanges = false;
  try {
    for (final entry in files.entries) {
      writeStringIfChanged(entry.value, sources[entry.key]!);
    }
    if (fullStack) {
      writeStringIfChanged(gitIgnore, _withGitIgnoreEntries(gitIgnore));
    }
    if (generateRoutes(project, out, err) == null) return false;

    out.writeln(
      wasCurrent
          ? fullStack
                ? 'Odroe full-stack starter is current.'
                : 'Odroe starter is current.'
          : fullStack
          ? 'Initialized the Odroe full-stack starter in ${project.root.path}.'
          : 'Initialized Odroe in ${project.root.path}.',
    );
    out.writeln('Next:');
    out.writeln('  dart run odroe dev --server-only');
    out.writeln('  dart run odroe dev -- -d chrome');
    if (fullStack) {
      out.writeln('Cloudflare local:');
      out.writeln('  npm ci');
      out.writeln('  dart run odroe build --no-server web');
      out.writeln('  npm run cloudflare:migrate:local');
      out.writeln('  npm run cloudflare:dev');
    } else {
      out.writeln('  dart run odroe build --no-server web');
    }
    keepChanges = true;
    return true;
  } finally {
    if (!keepChanges) _restore(snapshots, directories);
  }
}

void _validateFlutterApplication(CliProject project) {
  final metadata = File(p.join(project.root.path, '.metadata'));
  final metadataMap = _yamlMap(metadata, 'Flutter .metadata');
  if (metadataMap['project_type'] != 'app') {
    throw FileSystemException(
      'odroe init requires a Flutter application with '
      '`project_type: app` in .metadata.',
    );
  }

  final pubspec = _yamlMap(
    File(p.join(project.root.path, 'pubspec.yaml')),
    'pubspec.yaml',
  );
  final dependencies = pubspec['dependencies'];
  if (dependencies is! Map) {
    throw FileSystemException(
      'pubspec.yaml must declare Flutter and Odroe under dependencies.',
    );
  }
  final flutter = dependencies['flutter'];
  if (flutter is! Map || flutter['sdk'] != 'flutter') {
    throw FileSystemException(
      'pubspec.yaml must declare `flutter: {sdk: flutter}` under '
      'dependencies.',
    );
  }
  if (!dependencies.containsKey('odroe')) {
    throw FileSystemException(
      'pubspec.yaml must declare `odroe` under dependencies.',
    );
  }
}

Uri _validateOdroeResolution(CliProject project) {
  final configFile = File(
    p.join(project.root.path, '.dart_tool', 'package_config.json'),
  );
  if (!configFile.existsSync()) {
    throw FileSystemException(
      'Run `flutter pub get` in ${project.root.path} before `odroe init`.',
    );
  }

  final target = _resolvedPackageLibrary(configFile, 'odroe', 'odroe.dart');
  if (target == null) {
    throw FileSystemException(
      'Run `flutter pub get` after adding Odroe to ${project.root.path}.',
    );
  }
  final activeConfig = _activePackageConfig();
  final active = activeConfig == null
      ? null
      : _resolvedPackageLibrary(activeConfig, 'odroe', 'odroe.dart');
  if (active == null) {
    throw const FileSystemException(
      'The running Odroe package could not be resolved.',
    );
  }
  if (_canonicalFile(active) != _canonicalFile(target)) {
    throw FileSystemException(
      '${project.root.path} resolves a different Odroe checkout. Run '
      '`dart run odroe init` from that project after `flutter pub get`.',
    );
  }
  return active;
}

Map<String, String> _readFullStackSources(Uri odroeLibrary) {
  final packageRoot = File.fromUri(odroeLibrary).parent.parent;
  const manifest = <String, String>{
    'lib/main.dart': 'example/app/lib/main.dart',
    'lib/posts.dart': 'example/app/lib/posts.dart',
    'lib/posts_database.dart': 'example/app/lib/posts_database.dart',
    'lib/rpc_origin.dart': 'example/app/lib/rpc_origin.dart',
    'lib/server.dart': 'example/app/lib/server.dart',
    'lib/server_native.dart': 'example/app/lib/server_native.dart',
    'lib/server_cloudflare.dart': 'example/app/lib/server_cloudflare.dart',
    'migrations/0001_posts.sql': 'example/app/migrations/0001_posts.sql',
    'package.json': 'example/app/package.json',
    'package-lock.json': 'example/app/package-lock.json',
    'wrangler.jsonc': 'example/app/wrangler.jsonc',
  };
  final sources = <String, String>{};
  for (final entry in manifest.entries) {
    final file = File(p.join(packageRoot.path, entry.value));
    if (!file.existsSync()) {
      throw FileSystemException(
        'The Odroe package is missing a full-stack starter source.',
        file.path,
      );
    }
    sources[entry.key] = file.readAsStringSync();
  }
  for (final entry in <String, int>{
    'package.json': 1,
    'package-lock.json': 2,
    'wrangler.jsonc': 1,
  }.entries) {
    if ('odroe-example'.allMatches(sources[entry.key]!).length != entry.value) {
      throw FileSystemException(
        'The Odroe full-stack starter ${entry.key} is invalid.',
        manifest[entry.key],
      );
    }
  }
  return sources;
}

File? _activePackageConfig() {
  final configured = Platform.packageConfig;
  if (configured != null) {
    final uri = Uri.tryParse(configured);
    final file = uri != null && uri.scheme == 'file'
        ? File.fromUri(uri)
        : File(configured).absolute;
    if (file.existsSync()) return file;
  }

  var directory = Directory.current.absolute;
  while (true) {
    final file = File(
      p.join(directory.path, '.dart_tool', 'package_config.json'),
    );
    if (file.existsSync()) return file;
    final parent = directory.parent;
    if (parent.path == directory.path) return null;
    directory = parent;
  }
}

Uri? _resolvedPackageLibrary(
  File configFile,
  String packageName,
  String library,
) {
  Object? decoded;
  try {
    decoded = jsonDecode(configFile.readAsStringSync());
  } on Object {
    throw FileSystemException(
      '${configFile.path} is not a valid Dart package configuration.',
    );
  }
  if (decoded is! Map<String, Object?> || decoded['packages'] is! List) {
    throw FileSystemException(
      '${configFile.path} is not a valid Dart package configuration.',
    );
  }
  Map<String, Object?>? resolvedPackage;
  for (final package in decoded['packages']! as List<Object?>) {
    if (package is Map<String, Object?> && package['name'] == packageName) {
      resolvedPackage = package;
      break;
    }
  }
  final rootValue = resolvedPackage?['rootUri'];
  if (rootValue is! String) return null;
  try {
    final resolvedRoot = configFile.uri.resolve(rootValue);
    if (!_isLocalFileUri(resolvedRoot)) {
      throw const FormatException('rootUri must resolve to a local file URI.');
    }
    final root = resolvedRoot.path.endsWith('/')
        ? resolvedRoot
        : resolvedRoot.replace(path: '${resolvedRoot.path}/');
    final packageValue = resolvedPackage?['packageUri'];
    final packageUri = Uri.parse(packageValue is String ? packageValue : '');
    if (packageUri.isAbsolute ||
        packageUri.hasAuthority ||
        packageUri.path.startsWith('/') ||
        packageUri.hasQuery ||
        packageUri.hasFragment) {
      throw const FormatException('packageUri must be relative.');
    }
    final resolvedPackageRoot = root.resolveUri(packageUri);
    if (!_isLocalFileUri(resolvedPackageRoot)) {
      throw const FormatException(
        'Package root must resolve to a local file URI.',
      );
    }
    final packageRoot = resolvedPackageRoot.path.endsWith('/')
        ? resolvedPackageRoot
        : resolvedPackageRoot.replace(path: '${resolvedPackageRoot.path}/');
    final resolved = packageRoot.resolve(library);
    if (!_isLocalFileUri(resolved)) {
      throw const FormatException('Package library must be a local file URI.');
    }
    File.fromUri(resolved);
    return resolved;
  } on FormatException catch (error) {
    throw FileSystemException(
      '${configFile.path} has an invalid $packageName package URI: '
      '${error.message}',
    );
  } on ArgumentError catch (error) {
    throw FileSystemException(
      '${configFile.path} has an invalid $packageName package URI: $error',
    );
  } on UnsupportedError catch (error) {
    throw FileSystemException(
      '${configFile.path} has an invalid $packageName package URI: $error',
    );
  }
}

bool _isLocalFileUri(Uri uri) =>
    uri.scheme == 'file' &&
    uri.host.isEmpty &&
    !uri.hasQuery &&
    !uri.hasFragment;

Map<Object?, Object?> _yamlMap(File file, String name) {
  if (!file.existsSync()) {
    throw FileSystemException('$name does not exist.', file.path);
  }
  Object? value;
  try {
    value = loadYaml(file.readAsStringSync());
  } on Object {
    throw FileSystemException('$name is not valid YAML.', file.path);
  }
  if (value is! Map<Object?, Object?>) {
    throw FileSystemException('$name must contain a YAML map.', file.path);
  }
  return value;
}

void _validateSource(
  File file,
  List<String> allowed,
  Set<String> conflicts, {
  bool allowBlank = false,
}) {
  if (!file.existsSync()) return;
  final source = file.readAsStringSync();
  if (allowBlank && source.trim().isEmpty) return;
  if (allowed.any((expected) => _equivalentDart(source, expected))) return;
  conflicts.add(file.path);
}

void _validateTextSource(File file, String expected, Set<String> conflicts) {
  if (file.existsSync() && file.readAsStringSync() != expected) {
    conflicts.add(file.path);
  }
}

void _findUnexpectedDartSources(
  CliProject project, {
  required Set<String> allowed,
  required Set<String> conflicts,
}) {
  for (final directory in <Directory>[
    project.libDirectory,
    Directory(p.join(project.root.path, 'test')),
  ]) {
    if (!directory.existsSync()) continue;
    for (final entity in directory.listSync(
      recursive: true,
      followLinks: false,
    )) {
      if (entity is Link) {
        conflicts.add(entity.path);
        continue;
      }
      if (entity is! File || !entity.path.endsWith('.dart')) continue;
      if (!allowed.contains(p.normalize(entity.absolute.path))) {
        conflicts.add(entity.path);
      }
    }
  }
}

void _validateGeneratedFile(
  File file, {
  required bool starterRoutesExist,
  required String? expected,
  required Set<String> conflicts,
}) {
  if (!file.existsSync()) return;
  final source = file.readAsStringSync();
  if (starterRoutesExist &&
      (source == expected || source.startsWith(_generatedHeader))) {
    return;
  }
  conflicts.add(file.path);
}

bool _matches(File file, String expected) =>
    file.existsSync() && _equivalentDart(file.readAsStringSync(), expected);

bool _hasExactContents(File file, String expected) =>
    file.existsSync() && file.readAsStringSync() == expected;

bool _equivalentDart(String source, String expected) {
  try {
    return _formatter.format(source.replaceAll('\r\n', '\n')) ==
        _formatter.format(expected);
  } on FormatterException {
    return false;
  }
}

void _validateTargetPath(Directory root, File target, Set<String> conflicts) {
  var current = root.absolute.path;
  final relative = p.relative(target.absolute.path, from: current);
  final components = p.split(relative);
  for (var index = 0; index < components.length; index++) {
    final component = components[index];
    current = p.join(current, component);
    final type = FileSystemEntity.typeSync(current, followLinks: false);
    if (type == FileSystemEntityType.link) {
      throw FileSystemException(
        'odroe init will not write through a symbolic link: $current',
      );
    }
    final leaf = index == components.length - 1;
    if ((!leaf &&
            type != FileSystemEntityType.notFound &&
            type != FileSystemEntityType.directory) ||
        (leaf &&
            type != FileSystemEntityType.notFound &&
            type != FileSystemEntityType.file)) {
      conflicts.add(current);
      return;
    }
  }
}

Map<Directory, bool> _snapshotDirectories(
  Directory root,
  Iterable<File> files,
) {
  final rootPath = p.normalize(root.absolute.path);
  final paths = <String>{};
  for (final file in files) {
    var current = p.normalize(file.parent.absolute.path);
    while (current != rootPath && p.isWithin(rootPath, current)) {
      paths.add(current);
      current = p.dirname(current);
    }
  }
  return <Directory, bool>{
    for (final path in paths) Directory(path): Directory(path).existsSync(),
  };
}

const _gitIgnoreEntries = <String>['node_modules/', '.wrangler/', '.odroe/'];

bool _hasGitIgnoreEntries(File file) {
  if (!file.existsSync()) return false;
  final lines = const LineSplitter().convert(file.readAsStringSync());
  return _gitIgnoreEntries.every(lines.contains);
}

String _withGitIgnoreEntries(File file) {
  var source = file.existsSync() ? file.readAsStringSync() : '';
  final separator = source.contains('\r\n') ? '\r\n' : '\n';
  final lines = const LineSplitter().convert(source);
  for (final entry in _gitIgnoreEntries) {
    if (lines.contains(entry)) continue;
    if (source.isNotEmpty && !source.endsWith('\n') && !source.endsWith('\r')) {
      source += separator;
    }
    source += '$entry$separator';
  }
  return source;
}

String _canonicalFile(Uri uri) {
  final file = File.fromUri(uri);
  return file.existsSync()
      ? file.resolveSymbolicLinksSync()
      : p.normalize(file.absolute.path);
}

void _restore(
  Map<File, List<int>?> snapshots,
  Map<Directory, bool> directories,
) {
  for (final entry in snapshots.entries) {
    final bytes = entry.value;
    if (bytes == null) {
      if (entry.key.existsSync()) entry.key.deleteSync();
      continue;
    }
    entry.key.parent.createSync(recursive: true);
    entry.key.writeAsBytesSync(bytes, flush: true);
  }
  final directoryEntries = directories.entries.toList()
    ..sort(
      (left, right) =>
          p.split(right.key.path).length - p.split(left.key.path).length,
    );
  for (final entry in directoryEntries) {
    final directory = entry.key;
    if (!entry.value &&
        directory.existsSync() &&
        directory.listSync().isEmpty) {
      directory.deleteSync();
    }
  }
}

const _flutterEmptyMainSource = '''
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
''';

const _mainSource = '''
import 'package:flutter/material.dart';
import 'package:odroe/document_flutter.dart';
import 'package:odroe/odroe_flutter.dart';
import 'package:odroe/router_flutter.dart';

import 'routes.dart';

void main() {
  runApp(
    App(
      webPathUrls: true,
      modules: <Module>[
        DocumentModule(),
        RouterModule(routes: routeTree),
      ],
      builder: (app) => MaterialApp.router(
        routerConfig: app.read(routerKey),
      ),
    ),
  );
}
''';

const _routeSource = '''
import 'package:odroe/document.dart';
import 'package:odroe/router.dart';

final route =
    AppRoute<NoParams, NoSearch, NoData>(
      metadata: const RouteMetadata(
        title: 'Odroe App',
        description: 'A product built with Odroe.',
      ),
    ).document(
      (_) => const RouteDocument(
        language: 'en',
        body: HtmlElement(
          'main',
          children: <HtmlNode>[
            HtmlElement(
              'h1',
              children: <HtmlNode>[HtmlText('Hello from Odroe')],
            ),
          ],
        ),
      ),
    );
''';

const _pageSource = '''
import 'package:flutter/material.dart';
import 'package:odroe/router_flutter.dart';

import 'route.dart' as definition;

final route = definition.route.page(
  build: (_) => const Scaffold(
    body: Center(child: Text('Hello from Odroe')),
  ),
);
''';
