// ignore_for_file: public_member_api_docs

import 'dart:io';

import 'package:args/args.dart';
import 'package:odroe/router_compiler.dart';
import 'package:path/path.dart' as p;

final class CliProject {
  CliProject._({
    required this.root,
    required this.packageName,
    required this.compiler,
  });

  factory CliProject.from(ArgResults arguments) {
    final root = Directory(arguments.option('project')!).absolute;
    final pubspec = File(p.join(root.path, 'pubspec.yaml'));
    if (!pubspec.existsSync()) {
      throw FileSystemException('pubspec.yaml does not exist.', pubspec.path);
    }
    final match = RegExp(
      r'^name:\s*([A-Za-z_][A-Za-z0-9_]*)\s*$',
      multiLine: true,
    ).firstMatch(pubspec.readAsStringSync());
    if (match == null) {
      throw FormatException('pubspec.yaml must declare a valid package name.');
    }
    return CliProject._(
      root: root,
      packageName: match.group(1)!,
      compiler: FileRouteCompiler(
        projectRoot: root,
        routesPath: arguments.option('routes')!,
        outputPath: arguments.option('output')!,
        serverOutputPath: arguments.option('server-output')!,
      ),
    );
  }

  final Directory root;
  final String packageName;
  final FileRouteCompiler compiler;

  Directory get libDirectory => Directory(p.join(root.path, 'lib'));
  File get bootstrap =>
      File(p.join(root.path, '.dart_tool', 'odroe', 'server.dart'));

  void writeBootstrap() {
    final source = _bootstrapSource(packageName);
    bootstrap.parent.createSync(recursive: true);
    if (bootstrap.existsSync() && bootstrap.readAsStringSync() == source) {
      return;
    }
    final temporary = File('${bootstrap.path}.tmp');
    try {
      temporary.writeAsStringSync(source);
      temporary.renameSync(bootstrap.path);
    } finally {
      if (temporary.existsSync()) temporary.deleteSync();
    }
  }
}

FileRouteOutput? generateRoutes(
  CliProject project,
  StringSink out,
  StringSink err,
) {
  try {
    final result = project.compiler.write();
    project.writeBootstrap();
    out.writeln(
      result.changed
          ? 'Generated ${project.compiler.outputFile.path} and '
                '${project.compiler.serverOutputFile.path} '
                '(${result.routeCount} routes).'
          : 'Generated routes are current (${result.routeCount} routes).',
    );
    return result;
  } on FileRouteCompilationException catch (error) {
    for (final diagnostic in error.diagnostics) {
      err.writeln(diagnostic);
    }
    return null;
  }
}

Future<Process> startProjectProcess(
  String executable,
  List<String> arguments, {
  required CliProject project,
  Map<String, String>? environment,
}) => Process.start(
  executable,
  arguments,
  workingDirectory: project.root.path,
  environment: environment,
  mode: ProcessStartMode.inheritStdio,
);

String _bootstrapSource(String packageName) =>
    '''
// Generated by Odroe. Do not edit.
import 'dart:async';
import 'dart:io';

import 'package:odroe/start_io.dart';
import 'package:$packageName/routes.server.dart';

Future<void> main() async {
  final host = Platform.environment['ODROE_HOST'] ?? '127.0.0.1';
  final port = int.parse(Platform.environment['ODROE_PORT'] ?? '3000');
  final webRoot = Platform.environment['ODROE_WEB_ROOT'];
  final developmentOriginFile =
      Platform.environment['ODROE_FLUTTER_ORIGIN_FILE'];
  final server = await StartIoServer.bind(
    createStartApplication().handler,
    address: host,
    port: port,
    publicDirectory: webRoot == '' ? null : Directory(webRoot ?? 'build/web'),
    developmentProxyOriginFile: developmentOriginFile == null
        ? null
        : File(developmentOriginFile),
  );
  stdout.writeln(
    'Odroe Start listening on http://\${server.address.host}:\${server.port}',
  );
  if (!Platform.isWindows) {
    final stopping = Completer<void>();
    void stop(ProcessSignal _) {
      if (!stopping.isCompleted) stopping.complete();
    }
    final interrupt = ProcessSignal.sigint.watch().listen(stop);
    final terminate = ProcessSignal.sigterm.watch().listen(stop);
    await stopping.future;
    await interrupt.cancel();
    await terminate.cancel();
    await server.close(force: true);
  }
}
''';
