// Generated by Odroe. Do not edit.
// ignore_for_file: type=lint

import 'package:odroe/start.dart';
import 'routes/docs/[...slug]/route.dart' as _docsRestSlugDefinition;
import 'routes/posts/route.dart' as _postsDefinition;
import 'routes/posts/[postId]/route.dart' as _postsPostIdDefinition;
import 'routes/posts/[postId]/server.dart' as _postsPostIdServer;

final _serverRoutePostsPostId = _postsPostIdServer.route.compiled(
  path: "[postId]",
  terminal: true,
  params: PathParams<_postsPostIdDefinition.Params>.codec(
    decode: (input) => (postId: input.requiredInt('postId')),
    encode: (value, output) {
      output.integer('postId', value.postId);
    },
  ),
  search: SearchParams<_postsPostIdDefinition.Search>.codec(
    keys: const <String>{"preview", "tags"},
    defaults: _postsPostIdDefinition.route.search!.defaults,
    invalid: _postsPostIdDefinition.route.search!.invalid,
    decode: (input) => (
      preview:
          input.boolean('preview') ??
          _postsPostIdDefinition.route.search!.defaults.preview,
      tags: input.strings(
        'tags',
        fallback: _postsPostIdDefinition.route.search!.defaults.tags,
      ),
    ),
    encode: (value, output) {
      output.boolean(
        'preview',
        value.preview,
        omitIf: _postsPostIdDefinition.route.search!.defaults.preview,
      );
      output.strings(
        'tags',
        value.tags,
        omitIf: _postsPostIdDefinition.route.search!.defaults.tags,
      );
    },
  ),
);

final _serverRoutePosts = _postsDefinition.route.compiled(
  path: "posts",
  terminal: true,
  search: SearchParams<_postsDefinition.Search>.codec(
    keys: const <String>{"sort"},
    defaults: _postsDefinition.route.search!.defaults,
    invalid: _postsDefinition.route.search!.invalid,
    decode: (input) => (
      sort:
          input.string('sort') ?? _postsDefinition.route.search!.defaults.sort,
    ),
    encode: (value, output) {
      output.string(
        'sort',
        value.sort,
        omitIf: _postsDefinition.route.search!.defaults.sort,
      );
    },
  ),
  children: <AnyAppRoute>[_serverRoutePostsPostId],
);

final _serverRouteDocsRestSlug = _docsRestSlugDefinition.route.compiled(
  path: "[...slug]",
  terminal: true,
  params: PathParams<_docsRestSlugDefinition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _serverRouteDocs = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "docs",
  terminal: false,
  children: <AnyAppRoute>[_serverRouteDocsRestSlug],
);

final _serverRouteMarketingPricing = AppRoute<NoParams, NoSearch, NoData>()
    .compiled(path: "pricing", terminal: true);

final _serverRouteMarketing = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "",
  terminal: false,
  children: <AnyAppRoute>[_serverRouteMarketingPricing],
);

final _serverRouteAccountSettings = AppRoute<NoParams, NoSearch, NoData>()
    .compiled(path: "settings", terminal: true);

final _serverRouteAccount = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "",
  terminal: false,
  children: <AnyAppRoute>[_serverRouteAccountSettings],
);

final _serverRouteRoot = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "/",
  terminal: true,
  children: <AnyAppRoute>[
    _serverRouteAccount,
    _serverRouteMarketing,
    _serverRouteDocs,
    _serverRoutePosts,
  ],
);

final List<AnyAppRoute> serverRouteTree = <AnyAppRoute>[_serverRouteRoot];

final Map<String, AnyServerFunction> serverFunctions =
    <String, AnyServerFunction>{
      "lib/routes/posts/[postId]/server.dart#readTitle": _postsPostIdServer
          .readTitle
          .bind("lib/routes/posts/[postId]/server.dart#readTitle"),
      "lib/routes/posts/[postId]/server.dart#watchViews": _postsPostIdServer
          .watchViews
          .bind("lib/routes/posts/[postId]/server.dart#watchViews"),
      "lib/routes/posts/[postId]/server.dart#doubleValues": _postsPostIdServer
          .doubleValues
          .bind(
            "lib/routes/posts/[postId]/server.dart#doubleValues",
            decodeInput: (value) => (value as List)
                .map((item) => item as int)
                .toList(growable: false),
          ),
      "lib/routes/posts/[postId]/server.dart#normalizePost": _postsPostIdServer
          .normalizePost
          .bind("lib/routes/posts/[postId]/server.dart#normalizePost"),
    };

StartApplication createStartApplication({
  Iterable<StartMiddleware> middleware = const <StartMiddleware>[],
  StartSerializer? serializer,
  StartRenderer? renderer,
  StartOptions options = const StartOptions(),
}) => StartApplication(
  routes: serverRouteTree,
  functions: serverFunctions,
  middleware: middleware,
  serializer: serializer,
  renderer: renderer,
  options: options,
);
