// Generated by Odroe. Do not edit.
// ignore_for_file: type=lint

import 'package:odroe/router.dart';
import 'routes/page.dart' as _rootPage;
import 'routes/shell.dart' as _rootShell;
import 'routes/(account)/settings/page.dart' as _accountSettingsPage;
import 'routes/(marketing)/pricing/page.dart' as _marketingPricingPage;
import 'routes/docs/[...slug]/route.dart' as _docsRestSlugDefinition;
import 'routes/docs/[...slug]/page.dart' as _docsRestSlugPage;
import 'routes/posts/route.dart' as _postsDefinition;
import 'routes/posts/page.dart' as _postsPage;
import 'routes/posts/[postId]/route.dart' as _postsPostIdDefinition;
import 'routes/posts/[postId]/page.dart' as _postsPostIdPage;

final _routePostsPostId = _postsPostIdPage.route.compiled(
  path: "[postId]",
  terminal: true,
  params: PathParams<_postsPostIdDefinition.Params>.codec(
    decode: (input) => (postId: input.requiredInt('postId')),
    encode: (value, output) {
      output.integer('postId', value.postId);
    },
  ),
  search: SearchParams<_postsPostIdDefinition.Search>.codec(
    keys: const <String>{"preview", "tags"},
    defaults: _postsPostIdDefinition.route.search!.defaults,
    invalid: _postsPostIdDefinition.route.search!.invalid,
    decode: (input) => (
      preview:
          input.boolean('preview') ??
          _postsPostIdDefinition.route.search!.defaults.preview,
      tags: input.strings(
        'tags',
        fallback: _postsPostIdDefinition.route.search!.defaults.tags,
      ),
    ),
    encode: (value, output) {
      output.boolean(
        'preview',
        value.preview,
        omitIf: _postsPostIdDefinition.route.search!.defaults.preview,
      );
      output.strings(
        'tags',
        value.tags,
        omitIf: _postsPostIdDefinition.route.search!.defaults.tags,
      );
    },
  ),
);

final _routePosts = _postsPage.route.compiled(
  path: "posts",
  terminal: true,
  search: SearchParams<_postsDefinition.Search>.codec(
    keys: const <String>{"sort"},
    defaults: _postsDefinition.route.search!.defaults,
    invalid: _postsDefinition.route.search!.invalid,
    decode: (input) => (
      sort:
          input.string('sort') ?? _postsDefinition.route.search!.defaults.sort,
    ),
    encode: (value, output) {
      output.string(
        'sort',
        value.sort,
        omitIf: _postsDefinition.route.search!.defaults.sort,
      );
    },
  ),
  children: <AnyAppRoute>[_routePostsPostId],
);

final _routeDocsRestSlug = _docsRestSlugPage.route.compiled(
  path: "[...slug]",
  terminal: true,
  params: PathParams<_docsRestSlugDefinition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _routeDocs = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "docs",
  terminal: false,
  children: <AnyAppRoute>[_routeDocsRestSlug],
);

final _routeMarketingPricing = _marketingPricingPage.route.compiled(
  path: "pricing",
  terminal: true,
);

final _routeMarketing = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "",
  terminal: false,
  children: <AnyAppRoute>[_routeMarketingPricing],
);

final _routeAccountSettings = _accountSettingsPage.route.compiled(
  path: "settings",
  terminal: true,
);

final _routeAccount = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "",
  terminal: false,
  children: <AnyAppRoute>[_routeAccountSettings],
);

final _routeRoot = _rootShell.route
    .withPage(_rootPage.route)
    .compiled(
      path: "/",
      terminal: true,
      children: <AnyAppRoute>[
        _routeAccount,
        _routeMarketing,
        _routeDocs,
        _routePosts,
      ],
    );

final List<AnyAppRoute> routeTree = <AnyAppRoute>[_routeRoot];

const routes = AppRoutes();

final class AppRoutes {
  const AppRoutes();

  final AppAccountRoutes account = const AppAccountRoutes();

  final AppMarketingRoutes marketing = const AppMarketingRoutes();

  final AppDocsRoutes docs = const AppDocsRoutes();

  final AppPostsRoutes posts = const AppPostsRoutes();

  Destination to() {
    return _routeRoot.ref().destination;
  }
}

final class AppAccountRoutes {
  const AppAccountRoutes();

  final AppAccountSettingsRoutes settings = const AppAccountSettingsRoutes();
}

final class AppAccountSettingsRoutes {
  const AppAccountSettingsRoutes();

  Destination to() {
    return _routeRoot
        .ref()
        .then(_routeAccount.ref())
        .then(_routeAccountSettings.ref())
        .destination;
  }
}

final class AppMarketingRoutes {
  const AppMarketingRoutes();

  final AppMarketingPricingRoutes pricing = const AppMarketingPricingRoutes();
}

final class AppMarketingPricingRoutes {
  const AppMarketingPricingRoutes();

  Destination to() {
    return _routeRoot
        .ref()
        .then(_routeMarketing.ref())
        .then(_routeMarketingPricing.ref())
        .destination;
  }
}

final class AppDocsRoutes {
  const AppDocsRoutes();

  final AppDocsRestSlugRoutes restSlug = const AppDocsRestSlugRoutes();
}

final class AppDocsRestSlugRoutes {
  const AppDocsRestSlugRoutes();

  Destination to({required ({List<String> slug}) params}) {
    return _routeRoot
        .ref()
        .then(_routeDocs.ref())
        .then(_routeDocsRestSlug.ref(params: (slug: params.slug)))
        .destination;
  }
}

final class AppPostsRoutes {
  const AppPostsRoutes();

  final AppPostsPostIdRoutes postId = const AppPostsPostIdRoutes();

  Destination to({_postsDefinition.Search? search}) {
    return _routeRoot.ref().then(_routePosts.ref(search: search)).destination;
  }
}

final class AppPostsPostIdRoutes {
  const AppPostsPostIdRoutes();

  Destination to({
    required ({int postId}) params,
    _postsDefinition.Search? postsSearch,
    _postsPostIdDefinition.Search? search,
  }) {
    return _routeRoot
        .ref()
        .then(_routePosts.ref(search: postsSearch))
        .then(
          _routePostsPostId.ref(
            params: (postId: params.postId),
            search: search,
          ),
        )
        .destination;
  }
}
