import 'dart:convert';
import 'dart:io';

import 'package:odroe/src/cli/cli.dart';
import 'package:odroe/src/router_compiler/compiler.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  test('init creates one runnable product and is idempotent', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    final output = StringBuffer();
    final errors = StringBuffer();

    final code = await runOdroe(
      <String>['init', '--project', project.path],
      output: output,
      errors: errors,
    );

    expect(code, 0, reason: errors.toString());
    expect(errors, isEmpty);
    expect(output.toString(), contains('Initialized Odroe in'));
    expect(output.toString(), contains('dart run odroe dev --server-only'));
    expect(output.toString(), contains('dart run odroe dev -- -d chrome'));
    expect(output.toString(), contains('dart run odroe build --no-server web'));
    expect(output.toString(), isNot(contains('  dart run odroe build web')));
    final main = File(p.join(project.path, 'lib', 'main.dart'));
    final route = File(p.join(project.path, 'lib', 'routes', 'route.dart'));
    final page = File(p.join(project.path, 'lib', 'routes', 'page.dart'));
    final compiler = FileRouteCompiler(projectRoot: project);
    final bootstrap = File(
      p.join(project.path, '.dart_tool', 'odroe', 'server.dart'),
    );
    final generated = compiler.compile();
    expect(generated.diagnostics, isEmpty);
    expect(generated.routeCount, 1);
    expect(generated.staticRoutes, <String>['/']);
    expect(generated.hasFlutter, isTrue);
    expect(compiler.outputFile.readAsStringSync(), generated.source);
    expect(
      compiler.serverOutputFile.readAsStringSync(),
      generated.serverSource,
    );
    expect(main.readAsStringSync(), contains('DocumentModule()'));
    expect(
      main.readAsStringSync(),
      contains('RouterModule(routes: routeTree)'),
    );
    expect(route.readAsStringSync(), contains("HtmlText('Hello from Odroe')"));
    expect(page.readAsStringSync(), contains("Text('Hello from Odroe')"));
    expect(bootstrap.readAsStringSync(), startsWith('// Generated by Odroe.'));

    final files = <File>[
      main,
      route,
      page,
      compiler.outputFile,
      compiler.serverOutputFile,
      bootstrap,
    ];
    final unchangedTime = DateTime.utc(2001, 2, 3, 4, 5, 6);
    for (final file in files) {
      file.setLastModifiedSync(unchangedTime);
    }
    final secondOutput = StringBuffer();
    final secondCode = await runOdroe(
      <String>['init', '--project', project.path],
      output: secondOutput,
      errors: errors,
    );

    expect(secondCode, 0, reason: errors.toString());
    expect(secondOutput.toString(), contains('Odroe starter is current.'));
    for (final file in files) {
      expect(file.lastModifiedSync().toUtc(), unchangedTime, reason: file.path);
    }
  });

  test(
    'init rejects every custom Dart source without partial writes',
    () async {
      final cases = <String, void Function(Directory)>{
        'main': (project) => File(
          p.join(project.path, 'lib', 'main.dart'),
        ).writeAsStringSync('void main() {}\n'),
        'route': (project) =>
            File(p.join(project.path, 'lib', 'routes', 'route.dart'))
              ..createSync(recursive: true)
              ..writeAsStringSync('final route = Object();\n'),
        'test': (project) =>
            File(p.join(project.path, 'test', 'widget_test.dart'))
              ..createSync(recursive: true)
              ..writeAsStringSync('void main() {}\n'),
        'generated output': (project) => File(
          p.join(project.path, 'lib', 'routes.dart'),
        ).writeAsStringSync('// application-owned\n'),
      };

      for (final entry in cases.entries) {
        final project = await _createProject();
        addTearDown(() => project.delete(recursive: true));
        entry.value(project);
        final before = _snapshot(project);
        final errors = StringBuffer();

        final code = await runOdroe(
          <String>['init', '--project', project.path],
          output: StringBuffer(),
          errors: errors,
        );

        expect(code, 1, reason: entry.key);
        expect(
          errors.toString(),
          contains('will not overwrite'),
          reason: entry.key,
        );
        expect(_snapshot(project), before, reason: entry.key);
      }
    },
  );

  test('init requires a resolved Flutter application', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    File(p.join(project.path, '.metadata')).writeAsStringSync('''
project_type: package
''');
    final before = _snapshot(project);
    final errors = StringBuffer();

    final code = await runOdroe(
      <String>['init', '--project', project.path],
      output: StringBuffer(),
      errors: errors,
    );

    expect(code, 1);
    expect(errors.toString(), contains('project_type: app'));
    expect(_snapshot(project), before);
  });

  test('init restores original directory state when output fails', () async {
    for (final existingEmptyDirectories in <bool>[true, false]) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      final routes = Directory(p.join(project.path, 'lib', 'routes'));
      final bootstrap = Directory(p.join(project.path, '.dart_tool', 'odroe'));
      if (existingEmptyDirectories) {
        routes.createSync();
        bootstrap.createSync();
      } else {
        Directory(p.join(project.path, 'lib')).deleteSync(recursive: true);
      }
      final before = _snapshot(project);

      await expectLater(
        runOdroe(
          <String>['init', '--project', project.path],
          output: const _ThrowingSink(),
          errors: StringBuffer(),
        ),
        throwsA(isA<StateError>()),
        reason: 'existingEmptyDirectories=$existingEmptyDirectories',
      );

      expect(
        _snapshot(project),
        before,
        reason: 'existingEmptyDirectories=$existingEmptyDirectories',
      );
    }
  });

  test(
    'init normalizes equivalent starter source before reporting current',
    () async {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      expect(
        await runOdroe(
          <String>['init', '--project', project.path],
          output: StringBuffer(),
          errors: StringBuffer(),
        ),
        0,
      );
      final main = File(p.join(project.path, 'lib', 'main.dart'));
      main.writeAsStringSync(main.readAsStringSync().replaceAll('\n', '\r\n'));
      final output = StringBuffer();

      expect(
        await runOdroe(
          <String>['init', '--project', project.path],
          output: output,
          errors: StringBuffer(),
        ),
        0,
      );

      expect(output.toString(), contains('Initialized Odroe in'));
      expect(output.toString(), isNot(contains('Odroe starter is current.')));
      expect(main.readAsStringSync(), isNot(contains('\r')));
    },
  );

  test('init rejects a different resolved Odroe checkout', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    final other = Directory(p.join(project.path, 'other_odroe', 'lib'))
      ..createSync(recursive: true);
    File(p.join(other.path, 'odroe.dart')).writeAsStringSync('library;\n');
    _writePackageConfig(project, other.parent);
    final before = _snapshot(project);
    final errors = StringBuffer();

    final code = await runOdroe(
      <String>['init', '--project', project.path],
      output: StringBuffer(),
      errors: errors,
    );

    expect(code, 1);
    expect(errors.toString(), contains('different Odroe checkout'));
    expect(_snapshot(project), before);
  });

  test('init reports invalid package URIs without writing', () async {
    for (final rootUri in <String>[
      'https://example.com/odroe',
      'file:///tmp/odroe?revision=other',
      'file:///tmp/odroe#other',
    ]) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      _writePackageConfig(
        project,
        Directory.current.absolute,
        rootUri: rootUri,
      );
      final before = _snapshot(project);
      final errors = StringBuffer();

      final code = await runOdroe(
        <String>['init', '--project', project.path],
        output: StringBuffer(),
        errors: errors,
      );

      expect(code, 1, reason: rootUri);
      expect(errors.toString(), contains('invalid odroe package URI'));
      expect(_snapshot(project), before, reason: rootUri);
    }
  });

  test('init treats packageUri as a directory with a root default', () async {
    final cases = <({String rootUri, String? packageUri})>[
      (
        rootUri: Directory.current.absolute.uri.toString().replaceFirst(
          RegExp(r'/$'),
          '',
        ),
        packageUri: 'lib',
      ),
      (
        rootUri: Directory(
          p.join(Directory.current.path, 'lib'),
        ).absolute.uri.toString().replaceFirst(RegExp(r'/$'), ''),
        packageUri: null,
      ),
    ];

    for (final entry in cases) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      _writePackageConfig(
        project,
        Directory.current.absolute,
        rootUri: entry.rootUri,
        packageUri: entry.packageUri,
      );
      final errors = StringBuffer();

      final code = await runOdroe(
        <String>['init', '--project', project.path],
        output: StringBuffer(),
        errors: errors,
      );

      expect(code, 0, reason: errors.toString());
    }
  });

  test('help exposes init without accepting positional templates', () async {
    final help = StringBuffer();
    expect(await runOdroe(<String>['--help'], output: help), 0);
    expect(help.toString(), contains('init      Initialize'));

    final errors = StringBuffer();
    expect(
      await runOdroe(
        <String>['init', 'template'],
        output: StringBuffer(),
        errors: errors,
      ),
      64,
    );
    expect(errors.toString(), contains('does not accept positional'));
  });
}

Future<Directory> _createProject() async {
  final project = await Directory.systemTemp.createTemp('odroe_init_test_');
  File(p.join(project.path, '.metadata')).writeAsStringSync('''
project_type: app
''');
  File(p.join(project.path, 'pubspec.yaml')).writeAsStringSync('''
name: init_fixture
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  odroe:
    path: ${Directory.current.path}
''');
  final main = File(p.join(project.path, 'lib', 'main.dart'))
    ..createSync(recursive: true)
    ..writeAsStringSync(_flutterEmptyMain);
  expect(main.existsSync(), isTrue);
  _writePackageConfig(project, Directory.current.absolute);
  return project;
}

void _writePackageConfig(
  Directory project,
  Directory odroeRoot, {
  String? rootUri,
  String? packageUri = 'lib/',
}) {
  final config = File(p.join(project.path, '.dart_tool', 'package_config.json'))
    ..createSync(recursive: true);
  config.writeAsStringSync(
    jsonEncode(<String, Object?>{
      'configVersion': 2,
      'packages': <Object?>[
        <String, Object?>{
          'name': 'odroe',
          'rootUri':
              rootUri ??
              odroeRoot.uri.toString().replaceFirst(RegExp(r'/$'), ''),
          'packageUri': ?packageUri,
          'languageVersion': '3.10',
        },
      ],
    }),
  );
}

List<String> _snapshot(Directory root) {
  final entities = root.listSync(recursive: true, followLinks: false)
    ..sort((left, right) => left.path.compareTo(right.path));
  return <String>[
    for (final entity in entities)
      if (entity is File)
        'file:${p.relative(entity.path, from: root.path)}:'
            '${base64Encode(entity.readAsBytesSync())}'
      else if (entity is Link)
        'link:${p.relative(entity.path, from: root.path)}:${entity.targetSync()}'
      else
        'directory:${p.relative(entity.path, from: root.path)}',
  ];
}

const _flutterEmptyMain = '''
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
''';

final class _ThrowingSink implements StringSink {
  const _ThrowingSink();

  Never _fail() => throw StateError('Injected output failure.');

  @override
  void write(Object? object) => _fail();

  @override
  void writeAll(Iterable<Object?> objects, [String separator = '']) => _fail();

  @override
  void writeCharCode(int charCode) => _fail();

  @override
  void writeln([Object? object = '']) => _fail();
}
