@Timeout(Duration(minutes: 3))
library;

import 'dart:convert';
import 'dart:io';

import 'package:odroe/src/cli/cli.dart';
import 'package:odroe/src/router_compiler/compiler.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../support/dart_command_lock.dart';

void main() {
  test('init creates one runnable product and is idempotent', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    final output = StringBuffer();
    final errors = StringBuffer();

    final code = await runOdroe(
      <String>['init', '--project', project.path],
      output: output,
      errors: errors,
    );

    expect(code, 0, reason: errors.toString());
    expect(errors, isEmpty);
    expect(output.toString(), contains('Initialized Odroe in'));
    expect(output.toString(), contains('dart run odroe dev --server-only'));
    expect(output.toString(), contains('dart run odroe dev -- -d chrome'));
    expect(output.toString(), contains('dart run odroe build --no-server web'));
    expect(output.toString(), isNot(contains('  dart run odroe build web')));
    final main = File(p.join(project.path, 'lib', 'main.dart'));
    final route = File(p.join(project.path, 'lib', 'routes', 'route.dart'));
    final page = File(p.join(project.path, 'lib', 'routes', 'page.dart'));
    final compiler = FileRouteCompiler(projectRoot: project);
    final bootstrap = File(
      p.join(project.path, '.dart_tool', 'odroe', 'server.dart'),
    );
    final generated = compiler.compile();
    expect(generated.diagnostics, isEmpty);
    expect(generated.routeCount, 1);
    expect(generated.staticRoutes, <String>['/']);
    expect(generated.hasFlutter, isTrue);
    expect(compiler.outputFile.readAsStringSync(), generated.source);
    expect(
      compiler.serverOutputFile.readAsStringSync(),
      generated.serverSource,
    );
    expect(main.readAsStringSync(), contains('DocumentModule()'));
    expect(
      RegExp(r"import 'package:odroe/").allMatches(main.readAsStringSync()),
      hasLength(1),
    );
    expect(main.readAsStringSync(), contains('webPathUrls: true'));
    expect(
      main.readAsStringSync(),
      contains('RouterModule(routes: routeTree)'),
    );
    expect(route.readAsStringSync(), contains("HtmlText('Hello from Odroe')"));
    expect(page.readAsStringSync(), contains("Text('Hello from Odroe')"));
    expect(bootstrap.readAsStringSync(), startsWith('// Generated by Odroe.'));

    final files = <File>[
      main,
      route,
      page,
      compiler.outputFile,
      compiler.serverOutputFile,
      bootstrap,
    ];
    final unchangedTime = DateTime.utc(2001, 2, 3, 4, 5, 6);
    for (final file in files) {
      file.setLastModifiedSync(unchangedTime);
    }
    final secondOutput = StringBuffer();
    final secondCode = await runOdroe(
      <String>['init', '--project', project.path],
      output: secondOutput,
      errors: errors,
    );

    expect(secondCode, 0, reason: errors.toString());
    expect(secondOutput.toString(), contains('Odroe starter is current.'));
    for (final file in files) {
      expect(file.lastModifiedSync().toUtc(), unchangedTime, reason: file.path);
    }
  });

  test(
    'full-stack init creates one vertical product and is idempotent',
    () async {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      final output = StringBuffer();
      final errors = StringBuffer();

      final code = await runOdroe(
        <String>['init', '--full-stack', '--project', project.path],
        output: output,
        errors: errors,
      );

      expect(code, 0, reason: errors.toString());
      expect(errors, isEmpty);
      expect(output.toString(), contains('Odroe full-stack starter'));
      expect(output.toString(), contains('npm ci'));
      expect(
        output.toString(),
        contains('dart run odroe build --no-server web'),
      );
      final ownedFiles = <File>[
        for (final path in _fullStackFiles) File(p.join(project.path, path)),
      ];
      for (final file in ownedFiles) {
        expect(file.existsSync(), isTrue, reason: file.path);
      }
      final compiler = FileRouteCompiler(projectRoot: project);
      final generated = compiler.compile();
      expect(generated.diagnostics, isEmpty);
      expect(generated.routeCount, 1);
      expect(generated.staticRoutes, <String>['/']);
      expect(generated.hasFlutter, isTrue);
      expect(generated.source, contains('listPosts'));
      expect(generated.source, contains('createPost'));
      expect(generated.serverSource, contains('posts.list'));
      expect(generated.serverSource, contains('posts.create'));
      expect(compiler.outputFile.readAsStringSync(), generated.source);
      expect(
        compiler.serverOutputFile.readAsStringSync(),
        generated.serverSource,
      );
      final bootstrap = File(
        p.join(project.path, '.dart_tool', 'odroe', 'server.dart'),
      );
      expect(bootstrap.readAsStringSync(), contains('/server.dart'));
      final main = File(p.join(project.path, 'lib', 'main.dart'));
      expect(
        RegExp(r"import 'package:odroe/").allMatches(main.readAsStringSync()),
        hasLength(1),
      );

      final package =
          jsonDecode(
                File(p.join(project.path, 'package.json')).readAsStringSync(),
              )
              as Map<String, Object?>;
      expect(
        File(p.join(project.path, 'odroe.yaml')).readAsStringSync(),
        'sqlite_migrations: migrations\n',
      );
      final lock =
          jsonDecode(
                File(
                  p.join(project.path, 'package-lock.json'),
                ).readAsStringSync(),
              )
              as Map<String, Object?>;
      final wrangler =
          jsonDecode(
                File(p.join(project.path, 'wrangler.jsonc')).readAsStringSync(),
              )
              as Map<String, Object?>;
      expect(package['name'], 'init-fixture');
      expect(lock['name'], 'init-fixture');
      expect(
        ((lock['packages']! as Map<String, Object?>)['']!
            as Map<String, Object?>)['name'],
        'init-fixture',
      );
      expect(wrangler['name'], 'init-fixture');
      expect(
        (package['scripts']! as Map<String, Object?>)['cloudflare:dev'],
        'dart run odroe dev --server-target cloudflare --server-only',
      );
      final nativeServer = File(
        p.join(project.path, 'lib', 'server_native.dart'),
      ).readAsStringSync();
      final database = File(
        p.join(project.path, 'lib', 'posts_database.dart'),
      ).readAsStringSync();
      final models = File(
        p.join(project.path, 'lib', 'posts.dart'),
      ).readAsStringSync();
      final routeServer = File(
        p.join(project.path, 'lib', 'routes', 'server.dart'),
      ).readAsStringSync();
      final routePage = File(
        p.join(project.path, 'lib', 'routes', 'page.dart'),
      ).readAsStringSync();
      expect(nativeServer, contains('ODROE_SQLITE_PATH'));
      expect(nativeServer, contains('ODROE_MIGRATIONS_PATH'));
      expect(nativeServer, contains("'.odroe/app.sqlite3'"));
      expect(nativeServer, contains('databasePath.isEmpty'));
      expect(nativeServer, contains('SqliteDatabase.open(databaseFile.path)'));
      expect(nativeServer, contains('readSqliteMigrations(migrationsPath)'));
      expect(nativeServer, contains('database.applyMigrations(migrations)'));
      expect(database, isNot(contains('CREATE TABLE')));
      expect(database, contains("import 'posts.dart';"));
      expect(database, contains('SqlTable<Post>'));
      expect(database, contains('id: row.read(id)'));
      expect(database, contains('title: row.read(title)'));
      expect(database, isNot(contains('.read(row,')));
      expect(database, isNot(contains('INSERT INTO posts')));
      expect(models, contains('typedef Post = ({int id, String title});'));
      expect(models, contains('typedef CreatePost = ({String title});'));
      expect(models, contains('typedef PostPage ='));
      expect(models, contains('typedef ListPostsInput ='));
      expect(
        routeServer,
        contains('ServerFunction<models.ListPostsInput, models.PostPage>'),
      );
      expect(routeServer, contains("id: 'posts.list'"));
      expect(routeServer, contains("id: 'posts.create'"));
      expect(routeServer, contains('limit: input.limit + 1'));
      expect(routeServer, contains('posts.id.lessThan'));
      expect(routeServer, contains('.all('));
      expect(routeServer, contains('.returning(posts.projection)'));
      expect(routePage, contains('MutationBuilder<Post, CreatePost, void>'));
      expect(routePage, contains('InfiniteQueryBuilder<PostPage, int?>'));
      expect(routePage, contains('late MutationOptions'));
      expect(routePage, isNot(contains('late final MutationOptions')));
      expect(routePage, contains('void _configureCreate()'));
      expect(routePage, contains('_configureCreate();'));
      expect(
        routePage,
        contains('late InfiniteQueryOptions<PostPage, int?> _listOptions'),
      );
      expect(routePage, contains('options: _createOptions'));
      expect(routePage, contains('options: _listOptions'));
      expect(routePage, isNot(contains('options: MutationOptions')));
      expect(routePage, isNot(contains('options: InfiniteQueryOptions')));
      final gitIgnore = File(p.join(project.path, '.gitignore'));
      expect(
        const LineSplitter().convert(gitIgnore.readAsStringSync()),
        containsAll(<String>['node_modules/', '.wrangler/', '.odroe/']),
      );

      final files = <File>[
        ...ownedFiles,
        gitIgnore,
        compiler.outputFile,
        compiler.serverOutputFile,
        bootstrap,
      ];
      final unchangedTime = DateTime.utc(2001, 2, 3, 4, 5, 6);
      for (final file in files) {
        file.setLastModifiedSync(unchangedTime);
      }
      final secondOutput = StringBuffer();
      expect(
        await runOdroe(
          <String>['init', '--full-stack', '--project', project.path],
          output: secondOutput,
          errors: errors,
        ),
        0,
        reason: errors.toString(),
      );
      expect(
        secondOutput.toString(),
        contains('Odroe full-stack starter is current.'),
      );
      for (final file in files) {
        expect(
          file.lastModifiedSync().toUtc(),
          unchangedTime,
          reason: file.path,
        );
      }
    },
  );

  test('full-stack init upgrades the untouched basic starter', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    final errors = StringBuffer();
    expect(
      await runOdroe(
        <String>['init', '--project', project.path],
        output: StringBuffer(),
        errors: errors,
      ),
      0,
      reason: errors.toString(),
    );
    final output = StringBuffer();

    expect(
      await runOdroe(
        <String>['init', '--full-stack', '--project', project.path],
        output: output,
        errors: errors,
      ),
      0,
      reason: errors.toString(),
    );
    expect(output.toString(), contains('Odroe full-stack starter'));
    expect(
      FileRouteCompiler(projectRoot: project).compile().serverSource,
      allOf(contains('posts.list'), contains('posts.create')),
    );
  });

  test('init upgrades the previous Flutter composition imports', () async {
    for (final fixture in <({bool fullStack, String source})>[
      (fullStack: false, source: _legacyBasicMain),
      (fullStack: true, source: _legacyFullStackMain),
    ]) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      final main = File(p.join(project.path, 'lib', 'main.dart'))
        ..writeAsStringSync(fixture.source);
      final errors = StringBuffer();
      final arguments = <String>[
        'init',
        if (fixture.fullStack) '--full-stack',
        '--project',
        project.path,
      ];

      expect(
        await runOdroe(arguments, output: StringBuffer(), errors: errors),
        0,
        reason: errors.toString(),
      );
      final source = main.readAsStringSync();
      expect(
        RegExp(r"import 'package:odroe/").allMatches(source),
        hasLength(1),
      );
      expect(source, contains("package:odroe/odroe_flutter.dart"));
      expect(
        await runOdroe(arguments, output: StringBuffer(), errors: errors),
        0,
        reason: errors.toString(),
      );
      expect(main.readAsStringSync(), source);
    }
  });

  test('full-stack init emits an analyzable Flutter project', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    final pubGet = await withDartCommandLock(
      () => Process.run('flutter', <String>[
        'pub',
        'get',
        '--offline',
      ], workingDirectory: project.path),
    );
    expect(pubGet.exitCode, 0, reason: '${pubGet.stdout}\n${pubGet.stderr}');
    final errors = StringBuffer();
    expect(
      await runOdroe(
        <String>['init', '--full-stack', '--project', project.path],
        output: StringBuffer(),
        errors: errors,
      ),
      0,
      reason: errors.toString(),
    );

    final analyze = await withDartCommandLock(
      () => Process.run(dartExecutable, <String>[
        'analyze',
        '--fatal-infos',
      ], workingDirectory: project.path),
    );
    expect(analyze.exitCode, 0, reason: '${analyze.stdout}\n${analyze.stderr}');
  });

  test(
    'full-stack init rejects unsafe targets without partial writes',
    () async {
      final cases = <String, void Function(Directory, Directory)>{
        'custom text': (project, _) =>
            File(p.join(project.path, 'migrations', '0001_posts.sql'))
              ..createSync(recursive: true)
              ..writeAsStringSync('application owned\n'),
        'custom config': (project, _) =>
            File(p.join(project.path, 'odroe.yaml'))
              ..writeAsStringSync('sqlite_migrations: database/migrations\n'),
        'directory at leaf': (project, _) =>
            Directory(p.join(project.path, 'package.json')).createSync(),
        'file at parent': (project, _) => File(
          p.join(project.path, 'migrations'),
        ).writeAsStringSync('not a directory'),
        if (!Platform.isWindows)
          'linked parent': (project, outside) =>
              Link(p.join(project.path, 'migrations')).createSync(outside.path),
      };

      for (final entry in cases.entries) {
        final project = await _createProject();
        final outside = await Directory.systemTemp.createTemp(
          'odroe_init_out_',
        );
        addTearDown(() => project.delete(recursive: true));
        addTearDown(() => outside.delete(recursive: true));
        final sentinel = File(p.join(outside.path, 'sentinel'))
          ..writeAsStringSync('outside');
        entry.value(project, outside);
        final before = _snapshot(project);
        final errors = StringBuffer();

        final code = await runOdroe(
          <String>['init', '--full-stack', '--project', project.path],
          output: StringBuffer(),
          errors: errors,
        );

        expect(code, 1, reason: entry.key);
        expect(_snapshot(project), before, reason: entry.key);
        expect(sentinel.readAsStringSync(), 'outside', reason: entry.key);
      }
    },
  );

  test(
    'full-stack init restores every file and directory on output failure',
    () async {
      for (final existingDirectories in <bool>[true, false]) {
        final project = await _createProject();
        addTearDown(() => project.delete(recursive: true));
        if (existingDirectories) {
          Directory(p.join(project.path, 'lib', 'routes')).createSync();
          Directory(p.join(project.path, 'migrations')).createSync();
          Directory(
            p.join(project.path, '.dart_tool', 'odroe'),
          ).createSync(recursive: true);
        } else {
          Directory(p.join(project.path, 'lib')).deleteSync(recursive: true);
        }
        final before = _snapshot(project);

        await expectLater(
          runOdroe(
            <String>['init', '--full-stack', '--project', project.path],
            output: const _ThrowingSink(),
            errors: StringBuffer(),
          ),
          throwsA(isA<StateError>()),
          reason: 'existingDirectories=$existingDirectories',
        );

        expect(
          _snapshot(project),
          before,
          reason: 'existingDirectories=$existingDirectories',
        );
      }
    },
  );

  test(
    'init rejects every custom Dart source without partial writes',
    () async {
      final cases = <String, void Function(Directory)>{
        'main': (project) => File(
          p.join(project.path, 'lib', 'main.dart'),
        ).writeAsStringSync('void main() {}\n'),
        'route': (project) =>
            File(p.join(project.path, 'lib', 'routes', 'route.dart'))
              ..createSync(recursive: true)
              ..writeAsStringSync('final route = Object();\n'),
        'test': (project) =>
            File(p.join(project.path, 'test', 'widget_test.dart'))
              ..createSync(recursive: true)
              ..writeAsStringSync('void main() {}\n'),
        'generated output': (project) => File(
          p.join(project.path, 'lib', 'routes.dart'),
        ).writeAsStringSync('// application-owned\n'),
      };

      for (final entry in cases.entries) {
        final project = await _createProject();
        addTearDown(() => project.delete(recursive: true));
        entry.value(project);
        final before = _snapshot(project);
        final errors = StringBuffer();

        final code = await runOdroe(
          <String>['init', '--project', project.path],
          output: StringBuffer(),
          errors: errors,
        );

        expect(code, 1, reason: entry.key);
        expect(
          errors.toString(),
          contains('will not overwrite'),
          reason: entry.key,
        );
        expect(_snapshot(project), before, reason: entry.key);
      }
    },
  );

  test('init requires a resolved Flutter application', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    File(p.join(project.path, '.metadata')).writeAsStringSync('''
project_type: package
''');
    final before = _snapshot(project);
    final errors = StringBuffer();

    final code = await runOdroe(
      <String>['init', '--project', project.path],
      output: StringBuffer(),
      errors: errors,
    );

    expect(code, 1);
    expect(errors.toString(), contains('project_type: app'));
    expect(_snapshot(project), before);
  });

  test('init restores original directory state when output fails', () async {
    for (final existingEmptyDirectories in <bool>[true, false]) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      final routes = Directory(p.join(project.path, 'lib', 'routes'));
      final bootstrap = Directory(p.join(project.path, '.dart_tool', 'odroe'));
      if (existingEmptyDirectories) {
        routes.createSync();
        bootstrap.createSync();
      } else {
        Directory(p.join(project.path, 'lib')).deleteSync(recursive: true);
      }
      final before = _snapshot(project);

      await expectLater(
        runOdroe(
          <String>['init', '--project', project.path],
          output: const _ThrowingSink(),
          errors: StringBuffer(),
        ),
        throwsA(isA<StateError>()),
        reason: 'existingEmptyDirectories=$existingEmptyDirectories',
      );

      expect(
        _snapshot(project),
        before,
        reason: 'existingEmptyDirectories=$existingEmptyDirectories',
      );
    }
  });

  test(
    'init normalizes equivalent starter source before reporting current',
    () async {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      expect(
        await runOdroe(
          <String>['init', '--project', project.path],
          output: StringBuffer(),
          errors: StringBuffer(),
        ),
        0,
      );
      final main = File(p.join(project.path, 'lib', 'main.dart'));
      main.writeAsStringSync(main.readAsStringSync().replaceAll('\n', '\r\n'));
      final output = StringBuffer();

      expect(
        await runOdroe(
          <String>['init', '--project', project.path],
          output: output,
          errors: StringBuffer(),
        ),
        0,
      );

      expect(output.toString(), contains('Initialized Odroe in'));
      expect(output.toString(), isNot(contains('Odroe starter is current.')));
      expect(main.readAsStringSync(), isNot(contains('\r')));
    },
  );

  test('init rejects a different resolved Odroe checkout', () async {
    final project = await _createProject();
    addTearDown(() => project.delete(recursive: true));
    final other = Directory(p.join(project.path, 'other_odroe', 'lib'))
      ..createSync(recursive: true);
    File(p.join(other.path, 'odroe.dart')).writeAsStringSync('library;\n');
    _writePackageConfig(project, other.parent);
    final before = _snapshot(project);
    final errors = StringBuffer();

    final code = await runOdroe(
      <String>['init', '--project', project.path],
      output: StringBuffer(),
      errors: errors,
    );

    expect(code, 1);
    expect(errors.toString(), contains('different Odroe checkout'));
    expect(_snapshot(project), before);
  });

  test('init reports invalid package URIs without writing', () async {
    for (final rootUri in <String>[
      'https://example.com/odroe',
      'file:///tmp/odroe?revision=other',
      'file:///tmp/odroe#other',
    ]) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      _writePackageConfig(
        project,
        Directory.current.absolute,
        rootUri: rootUri,
      );
      final before = _snapshot(project);
      final errors = StringBuffer();

      final code = await runOdroe(
        <String>['init', '--project', project.path],
        output: StringBuffer(),
        errors: errors,
      );

      expect(code, 1, reason: rootUri);
      expect(errors.toString(), contains('invalid odroe package URI'));
      expect(_snapshot(project), before, reason: rootUri);
    }
  });

  test('init treats packageUri as a directory with a root default', () async {
    final cases = <({String rootUri, String? packageUri})>[
      (
        rootUri: Directory.current.absolute.uri.toString().replaceFirst(
          RegExp(r'/$'),
          '',
        ),
        packageUri: 'lib',
      ),
      (
        rootUri: Directory(
          p.join(Directory.current.path, 'lib'),
        ).absolute.uri.toString().replaceFirst(RegExp(r'/$'), ''),
        packageUri: null,
      ),
    ];

    for (final entry in cases) {
      final project = await _createProject();
      addTearDown(() => project.delete(recursive: true));
      _writePackageConfig(
        project,
        Directory.current.absolute,
        rootUri: entry.rootUri,
        packageUri: entry.packageUri,
      );
      final errors = StringBuffer();

      final code = await runOdroe(
        <String>['init', '--project', project.path],
        output: StringBuffer(),
        errors: errors,
      );

      expect(code, 0, reason: errors.toString());
    }
  });

  test('help exposes init without accepting positional templates', () async {
    final help = StringBuffer();
    expect(await runOdroe(<String>['--help'], output: help), 0);
    expect(help.toString(), contains('init      Initialize'));

    final initHelp = StringBuffer();
    expect(await runOdroe(<String>['init', '--help'], output: initHelp), 0);
    expect(initHelp.toString(), contains('--full-stack'));

    final errors = StringBuffer();
    expect(
      await runOdroe(
        <String>['init', 'template'],
        output: StringBuffer(),
        errors: errors,
      ),
      64,
    );
    expect(errors.toString(), contains('does not accept positional'));
  });
}

const _fullStackFiles = <String>[
  'lib/main.dart',
  'lib/posts.dart',
  'lib/posts_database.dart',
  'lib/rpc_origin.dart',
  'lib/server.dart',
  'lib/server_native.dart',
  'lib/server_cloudflare.dart',
  'lib/routes/route.dart',
  'lib/routes/page.dart',
  'lib/routes/server.dart',
  'migrations/0001_posts.sql',
  'migrations/0002_unify_posts.sql',
  'odroe.yaml',
  'package.json',
  'package-lock.json',
  'wrangler.jsonc',
];

const _legacyBasicMain = '''
import 'package:flutter/material.dart';
import 'package:odroe/document_flutter.dart';
import 'package:odroe/odroe_flutter.dart';
import 'package:odroe/router_flutter.dart';

import 'routes.dart';

void main() {
  runApp(
    App(
      webPathUrls: true,
      modules: <Module>[
        DocumentModule(),
        RouterModule(routes: routeTree),
      ],
      builder: (app) => MaterialApp.router(
        routerConfig: app.read(routerKey),
      ),
    ),
  );
}
''';

const _legacyFullStackMain = '''
import 'package:flutter/material.dart';
import 'package:odroe/document_flutter.dart';
import 'package:odroe/odroe_flutter.dart';
import 'package:odroe/query_flutter.dart';
import 'package:odroe/router_flutter.dart';
import 'package:odroe/rpc.dart';

import 'rpc_origin.dart';
import 'routes.dart';

void main() {
  runApp(
    App(
      webPathUrls: true,
      modules: <Module>[
        QueryModule(),
        RpcModule.http(baseUri: rpcBaseUri()),
        DocumentModule(),
        RouterModule(routes: routeTree),
      ],
      builder: (app) => MaterialApp.router(routerConfig: app.read(routerKey)),
    ),
  );
}
''';

Future<Directory> _createProject() async {
  final project = await Directory.systemTemp.createTemp('odroe_init_test_');
  File(p.join(project.path, '.metadata')).writeAsStringSync('''
project_type: app
''');
  File(p.join(project.path, 'pubspec.yaml')).writeAsStringSync('''
name: init_fixture
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  odroe:
    path: ${Directory.current.path}
''');
  final main = File(p.join(project.path, 'lib', 'main.dart'))
    ..createSync(recursive: true)
    ..writeAsStringSync(_flutterEmptyMain);
  expect(main.existsSync(), isTrue);
  _writePackageConfig(project, Directory.current.absolute);
  return project;
}

void _writePackageConfig(
  Directory project,
  Directory odroeRoot, {
  String? rootUri,
  String? packageUri = 'lib/',
}) {
  final config = File(p.join(project.path, '.dart_tool', 'package_config.json'))
    ..createSync(recursive: true);
  config.writeAsStringSync(
    jsonEncode(<String, Object?>{
      'configVersion': 2,
      'packages': <Object?>[
        <String, Object?>{
          'name': 'odroe',
          'rootUri':
              rootUri ??
              odroeRoot.uri.toString().replaceFirst(RegExp(r'/$'), ''),
          'packageUri': ?packageUri,
          'languageVersion': '3.10',
        },
      ],
    }),
  );
}

List<String> _snapshot(Directory root) {
  final entities = root.listSync(recursive: true, followLinks: false)
    ..sort((left, right) => left.path.compareTo(right.path));
  return <String>[
    for (final entity in entities)
      if (entity is File)
        'file:${p.relative(entity.path, from: root.path)}:'
            '${base64Encode(entity.readAsBytesSync())}'
      else if (entity is Link)
        'link:${p.relative(entity.path, from: root.path)}:${entity.targetSync()}'
      else
        'directory:${p.relative(entity.path, from: root.path)}',
  ];
}

const _flutterEmptyMain = '''
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
''';

final class _ThrowingSink implements StringSink {
  const _ThrowingSink();

  Never _fail() => throw StateError('Injected output failure.');

  @override
  void write(Object? object) => _fail();

  @override
  void writeAll(Iterable<Object?> objects, [String separator = '']) => _fail();

  @override
  void writeCharCode(int charCode) => _fail();

  @override
  void writeln([Object? object = '']) => _fail();
}
