// Generated by Odroe. Do not edit.

import 'package:odroe/odroe.dart';
import 'package:odroe/router.dart';
import 'package:odroe/rpc.dart';
import 'package:odroe/server.dart';
import 'package:odroe/document.dart';
import 'routes/route.dart' as root_definition;
import 'routes/(account)/settings/route.dart' as account_settings_definition;
import 'routes/(marketing)/pricing/route.dart' as marketing_pricing_definition;
import 'routes/about/route.dart' as about_definition;
import 'routes/docs/[...slug]/route.dart' as docs_rest_slug_definition;
import 'routes/posts/route.dart' as posts_definition;
import 'routes/posts/[postId]/route.dart' as posts_post_id_definition;
import 'routes/posts/[postId]/server.dart' as posts_post_id_server;

final _serverRoutePostsPostId = posts_post_id_server.route.compiled(
  path: ":postId",
  terminal: true,
  params: PathParams<posts_post_id_definition.Params>.codec(
    decode: (input) => (postId: input.requiredInt('postId')),
    encode: (value, output) {
      output.integer('postId', value.postId);
    },
  ),
  search: SearchParams<posts_post_id_definition.Search>.codec(
    keys: const <String>{"preview", "tags"},
    defaults: posts_post_id_definition.route.search!.defaults,
    invalid: posts_post_id_definition.route.search!.invalid,
    decode: (input) => (
      preview:
          input.boolean('preview') ??
          posts_post_id_definition.route.search!.defaults.preview,
      tags: input.strings(
        'tags',
        fallback: posts_post_id_definition.route.search!.defaults.tags,
      ),
    ),
    encode: (value, output) {
      output.boolean(
        'preview',
        value.preview,
        omitIf: posts_post_id_definition.route.search!.defaults.preview,
      );
      output.strings(
        'tags',
        value.tags,
        omitIf: posts_post_id_definition.route.search!.defaults.tags,
      );
    },
  ),
);

final _serverRoutePosts = posts_definition.route.compiled(
  path: "posts",
  terminal: true,
  search: SearchParams<posts_definition.Search>.codec(
    keys: const <String>{"sort"},
    defaults: posts_definition.route.search!.defaults,
    invalid: posts_definition.route.search!.invalid,
    decode: (input) => (
      sort:
          input.string('sort') ?? posts_definition.route.search!.defaults.sort,
    ),
    encode: (value, output) {
      output.string(
        'sort',
        value.sort,
        omitIf: posts_definition.route.search!.defaults.sort,
      );
    },
  ),
  children: <RouteNode>[_serverRoutePostsPostId],
);

final _serverRouteDocsRestSlug = docs_rest_slug_definition.route.compiled(
  path: "docs/**:slug",
  terminal: true,
  params: PathParams<docs_rest_slug_definition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _serverRouteAbout = about_definition.route.compiled(
  path: "about",
  terminal: true,
);

final _serverRouteMarketingPricing = marketing_pricing_definition.route
    .compiled(path: "pricing", terminal: true);

final _serverRouteAccountSettings = account_settings_definition.route.compiled(
  path: "settings",
  terminal: true,
);

final _serverRouteRoot = root_definition.route.compiled(
  path: "/",
  terminal: true,
  children: <RouteNode>[
    _serverRouteAccountSettings,
    _serverRouteMarketingPricing,
    _serverRouteAbout,
    _serverRouteDocsRestSlug,
    _serverRoutePosts,
  ],
);

/// Compiled server route tree.
final List<RouteNode> serverRouteTree = <RouteNode>[_serverRouteRoot];

/// Server functions addressable by generated clients.
final serverFunctions = <String, ServerFunctionBinding>{
  "lib/routes/posts/[postId]/server.dart#readTitle": ServerFunctionBinding(
    posts_post_id_server.readTitle,
  ),
  "lib/routes/posts/[postId]/server.dart#watchViews": ServerFunctionBinding(
    posts_post_id_server.watchViews,
  ),
  "lib/routes/posts/[postId]/server.dart#doubleValues": ServerFunctionBinding(
    posts_post_id_server.doubleValues,
    decodeInput: (value) =>
        (value as List).map((item) => item as int).toList(growable: false),
  ),
  "lib/routes/posts/[postId]/server.dart#normalizePost": ServerFunctionBinding(
    posts_post_id_server.normalizePost,
  ),
};

/// Creates the application server from generated routes.
Server createServer({
  Iterable<Module> Function()? modules,
  Iterable<Middleware> middleware = const <Middleware>[],
  Serializer? serializer,
  Renderer? renderer,
}) => Server(
  routes: serverRouteTree,
  functions: serverFunctions,
  modules: modules,
  flutterRoutes: <RouteNode>[
    _serverRouteRoot,
    _serverRouteAccountSettings,
    _serverRouteMarketingPricing,
    _serverRouteDocsRestSlug,
    _serverRoutePosts,
    _serverRoutePostsPostId,
  ],
  middleware: middleware,
  serializer: serializer,
  renderer:
      renderer ??
      const DocumentRenderer(
        flutterBootstrap: '/flutter_bootstrap.js',
        baseHref: '/',
      ).call,
);
