// Generated by Odroe. Do not edit.
// ignore_for_file: type=lint

import 'package:odroe/route.dart';
import 'package:odroe/server.dart';
import 'routes/route.dart' as _rootDefinition;
import 'routes/about/route.dart' as _aboutDefinition;
import 'routes/docs/[...slug]/route.dart' as _docsRestSlugDefinition;
import 'routes/posts/route.dart' as _postsDefinition;
import 'routes/posts/[postId]/route.dart' as _postsPostIdDefinition;
import 'routes/posts/[postId]/server.dart' as _postsPostIdServer;

final _serverRoutePostsPostId = _postsPostIdServer.route.compiled(
  path: "[postId]",
  terminal: true,
  hasFlutterPage: true,
  params: PathParams<_postsPostIdDefinition.Params>.codec(
    decode: (input) => (postId: input.requiredInt('postId')),
    encode: (value, output) {
      output.integer('postId', value.postId);
    },
  ),
  search: SearchParams<_postsPostIdDefinition.Search>.codec(
    keys: const <String>{"preview", "tags"},
    defaults: _postsPostIdDefinition.route.search!.defaults,
    invalid: _postsPostIdDefinition.route.search!.invalid,
    decode: (input) => (
      preview:
          input.boolean('preview') ??
          _postsPostIdDefinition.route.search!.defaults.preview,
      tags: input.strings(
        'tags',
        fallback: _postsPostIdDefinition.route.search!.defaults.tags,
      ),
    ),
    encode: (value, output) {
      output.boolean(
        'preview',
        value.preview,
        omitIf: _postsPostIdDefinition.route.search!.defaults.preview,
      );
      output.strings(
        'tags',
        value.tags,
        omitIf: _postsPostIdDefinition.route.search!.defaults.tags,
      );
    },
  ),
);

final _serverRoutePosts = _postsDefinition.route.compiled(
  path: "posts",
  terminal: true,
  hasFlutterPage: true,
  search: SearchParams<_postsDefinition.Search>.codec(
    keys: const <String>{"sort"},
    defaults: _postsDefinition.route.search!.defaults,
    invalid: _postsDefinition.route.search!.invalid,
    decode: (input) => (
      sort:
          input.string('sort') ?? _postsDefinition.route.search!.defaults.sort,
    ),
    encode: (value, output) {
      output.string(
        'sort',
        value.sort,
        omitIf: _postsDefinition.route.search!.defaults.sort,
      );
    },
  ),
  children: <RouteNode>[_serverRoutePostsPostId],
);

final _serverRouteDocsRestSlug = _docsRestSlugDefinition.route.compiled(
  path: "[...slug]",
  terminal: true,
  hasFlutterPage: true,
  params: PathParams<_docsRestSlugDefinition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _serverRouteDocs = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "docs",
  terminal: false,
  hasFlutterPage: false,
  children: <RouteNode>[_serverRouteDocsRestSlug],
);

final _serverRouteAbout = _aboutDefinition.route.compiled(
  path: "about",
  terminal: true,
  hasFlutterPage: false,
);

final _serverRouteMarketingPricing = AppRoute<NoParams, NoSearch, NoData>()
    .compiled(path: "pricing", terminal: true, hasFlutterPage: true);

final _serverRouteMarketing = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "",
  terminal: false,
  hasFlutterPage: false,
  children: <RouteNode>[_serverRouteMarketingPricing],
);

final _serverRouteAccountSettings = AppRoute<NoParams, NoSearch, NoData>()
    .compiled(path: "settings", terminal: true, hasFlutterPage: true);

final _serverRouteAccount = AppRoute<NoParams, NoSearch, NoData>().compiled(
  path: "",
  terminal: false,
  hasFlutterPage: false,
  children: <RouteNode>[_serverRouteAccountSettings],
);

final _serverRouteRoot = _rootDefinition.route.compiled(
  path: "/",
  terminal: true,
  hasFlutterPage: true,
  children: <RouteNode>[
    _serverRouteAccount,
    _serverRouteMarketing,
    _serverRouteAbout,
    _serverRouteDocs,
    _serverRoutePosts,
  ],
);

final List<RouteNode> serverRouteTree = <RouteNode>[_serverRouteRoot];

final serverFunctions = <String, ServerFunctionBinding>{
  "lib/routes/posts/[postId]/server.dart#readTitle": ServerFunctionBinding(
    _postsPostIdServer.readTitle,
  ),
  "lib/routes/posts/[postId]/server.dart#watchViews": ServerFunctionBinding(
    _postsPostIdServer.watchViews,
  ),
  "lib/routes/posts/[postId]/server.dart#doubleValues": ServerFunctionBinding(
    _postsPostIdServer.doubleValues,
    decodeInput: (value) =>
        (value as List).map((item) => item as int).toList(growable: false),
  ),
  "lib/routes/posts/[postId]/server.dart#normalizePost": ServerFunctionBinding(
    _postsPostIdServer.normalizePost,
  ),
};

OdroeServer createServer({
  Iterable<Middleware> middleware = const <Middleware>[],
  Serializer? serializer,
  Renderer? renderer,
}) => OdroeServer(
  routes: serverRouteTree,
  functions: serverFunctions,
  middleware: middleware,
  serializer: serializer,
  renderer: renderer,
);
