// Generated by Odroe. Do not edit.

import 'package:odroe/router.dart';
import 'package:odroe/rpc.dart';
import 'models.dart' as posts_post_id_models_type;
import 'routes/page.dart' as root_page;
import 'routes/shell.dart' as root_shell;
import 'routes/(account)/settings/page.dart' as account_settings_page;
import 'routes/(marketing)/pricing/page.dart' as marketing_pricing_page;
import 'routes/about/route.dart' as about_definition;
import 'routes/docs/[...slug]/route.dart' as docs_rest_slug_definition;
import 'routes/docs/[...slug]/page.dart' as docs_rest_slug_page;
import 'routes/posts/route.dart' as posts_definition;
import 'routes/posts/page.dart' as posts_page;
import 'routes/posts/[postId]/route.dart' as posts_post_id_definition;
import 'routes/posts/[postId]/page.dart' as posts_post_id_page;

final _routePostsPostId = posts_post_id_page.route.compiled(
  path: ":postId",
  terminal: true,
  params: PathParams<posts_post_id_definition.Params>.codec(
    decode: (input) => (postId: input.requiredInt('postId')),
    encode: (value, output) {
      output.integer('postId', value.postId);
    },
  ),
  search: SearchParams<posts_post_id_definition.Search>.codec(
    keys: const <String>{"preview", "tags"},
    defaults: posts_post_id_definition.route.search!.defaults,
    invalid: posts_post_id_definition.route.search!.invalid,
    decode: (input) => (
      preview:
          input.boolean('preview') ??
          posts_post_id_definition.route.search!.defaults.preview,
      tags: input.strings(
        'tags',
        fallback: posts_post_id_definition.route.search!.defaults.tags,
      ),
    ),
    encode: (value, output) {
      output.boolean(
        'preview',
        value.preview,
        omitIf: posts_post_id_definition.route.search!.defaults.preview,
      );
      output.strings(
        'tags',
        value.tags,
        omitIf: posts_post_id_definition.route.search!.defaults.tags,
      );
    },
  ),
);

final _routePosts = posts_page.route.compiled(
  path: "posts",
  terminal: true,
  search: SearchParams<posts_definition.Search>.codec(
    keys: const <String>{"sort"},
    defaults: posts_definition.route.search!.defaults,
    invalid: posts_definition.route.search!.invalid,
    decode: (input) => (
      sort:
          input.string('sort') ?? posts_definition.route.search!.defaults.sort,
    ),
    encode: (value, output) {
      output.string(
        'sort',
        value.sort,
        omitIf: posts_definition.route.search!.defaults.sort,
      );
    },
  ),
  children: <RouteNode>[_routePostsPostId],
);

final _routeDocsRestSlug = docs_rest_slug_page.route.compiled(
  path: "docs/**:slug",
  terminal: true,
  params: PathParams<docs_rest_slug_definition.Params>.codec(
    decode: (input) => (slug: input.segments('slug')),
    encode: (value, output) {
      output.segments('slug', value.slug);
    },
  ),
);

final _routeAbout = about_definition.route.compiled(
  path: "about",
  terminal: true,
);

final _routeMarketingPricing = marketing_pricing_page.route.compiled(
  path: "pricing",
  terminal: true,
);

final _routeAccountSettings = account_settings_page.route.compiled(
  path: "settings",
  terminal: true,
);

final _routeRoot = root_shell.route
    .withPage(root_page.route)
    .compiled(
      path: "/",
      terminal: true,
      children: <RouteNode>[
        _routeAccountSettings,
        _routeMarketingPricing,
        _routeAbout,
        _routeDocsRestSlug,
        _routePosts,
      ],
    );

/// Compiled client route tree.
final List<RouteNode> routeTree = <RouteNode>[_routeRoot];

/// Typed references to filesystem routes.
const routes = AppRoutes();

/// Typed references below filesystem route "/".
final class AppRoutes {
  /// Creates a stateless route reference group.
  const AppRoutes();

  /// Routes below filesystem route "/(account)".
  final AppAccountRoutes account = const AppAccountRoutes();

  /// Routes below filesystem route "/(marketing)".
  final AppMarketingRoutes marketing = const AppMarketingRoutes();

  /// Routes below filesystem route "/about".
  final AppAboutRoutes about = const AppAboutRoutes();

  /// Routes below filesystem route "/docs".
  final AppDocsRoutes docs = const AppDocsRoutes();

  /// Routes below filesystem route "/posts".
  final AppPostsRoutes posts = const AppPostsRoutes();

  /// Builds a destination for this route.
  Destination to() {
    return _routeRoot.ref().destination;
  }
}

/// Typed references below filesystem route "/(account)".
final class AppAccountRoutes {
  /// Creates a stateless route reference group.
  const AppAccountRoutes();

  /// Routes below filesystem route "/(account)/settings".
  final AppAccountSettingsRoutes settings = const AppAccountSettingsRoutes();
}

/// Typed references below filesystem route "/(account)/settings".
final class AppAccountSettingsRoutes {
  /// Creates a stateless route reference group.
  const AppAccountSettingsRoutes();

  /// Builds a destination for this route.
  Destination to() {
    return _routeRoot.ref().then(_routeAccountSettings.ref()).destination;
  }
}

/// Typed references below filesystem route "/(marketing)".
final class AppMarketingRoutes {
  /// Creates a stateless route reference group.
  const AppMarketingRoutes();

  /// Routes below filesystem route "/(marketing)/pricing".
  final AppMarketingPricingRoutes pricing = const AppMarketingPricingRoutes();
}

/// Typed references below filesystem route "/(marketing)/pricing".
final class AppMarketingPricingRoutes {
  /// Creates a stateless route reference group.
  const AppMarketingPricingRoutes();

  /// Builds a destination for this route.
  Destination to() {
    return _routeRoot.ref().then(_routeMarketingPricing.ref()).destination;
  }
}

/// Typed references below filesystem route "/about".
final class AppAboutRoutes {
  /// Creates a stateless route reference group.
  const AppAboutRoutes();
}

/// Typed references below filesystem route "/docs".
final class AppDocsRoutes {
  /// Creates a stateless route reference group.
  const AppDocsRoutes();

  /// Routes below filesystem route "/docs/[...slug]".
  final AppDocsRestSlugRoutes restSlug = const AppDocsRestSlugRoutes();
}

/// Typed references below filesystem route "/docs/[...slug]".
final class AppDocsRestSlugRoutes {
  /// Creates a stateless route reference group.
  const AppDocsRestSlugRoutes();

  /// Builds a destination for this route.
  Destination to({required ({List<String> slug}) params}) {
    return _routeRoot
        .ref()
        .then(_routeDocsRestSlug.ref(params: (slug: params.slug)))
        .destination;
  }
}

/// Typed references below filesystem route "/posts".
final class AppPostsRoutes {
  /// Creates a stateless route reference group.
  const AppPostsRoutes();

  /// Routes below filesystem route "/posts/[postId]".
  final AppPostsPostIdRoutes postId = const AppPostsPostIdRoutes();

  /// Builds a destination for this route.
  Destination to({posts_definition.Search? search}) {
    return _routeRoot.ref().then(_routePosts.ref(search: search)).destination;
  }
}

/// Typed references below filesystem route "/posts/[postId]".
final class AppPostsPostIdRoutes {
  /// Creates a stateless route reference group.
  const AppPostsPostIdRoutes();

  /// Calls `readTitle` on the application server.
  ServerFunctionRef<int, String> get readTitle =>
      const ServerFunctionRef<int, String>(
        id: "lib/routes/posts/[postId]/server.dart#readTitle",
        method: HttpMethod.get,
      );

  /// Calls `watchViews` on the application server.
  ServerStreamFunctionRef<NoServerInput, int> get watchViews =>
      const ServerStreamFunctionRef<NoServerInput, int>(
        id: "lib/routes/posts/[postId]/server.dart#watchViews",
        method: HttpMethod.post,
      );

  /// Calls `doubleValues` on the application server.
  ServerFunctionRef<List<int>, List<int>> get doubleValues =>
      ServerFunctionRef<List<int>, List<int>>(
        id: "lib/routes/posts/[postId]/server.dart#doubleValues",
        method: HttpMethod.post,
        decodeOutput: (value) =>
            (value as List).map((item) => item as int).toList(growable: false),
      );

  /// Calls `normalizePost` on the application server.
  ServerFunctionRef<
    posts_post_id_models_type.PostId,
    posts_post_id_models_type.PostId
  >
  get normalizePost =>
      const ServerFunctionRef<
        posts_post_id_models_type.PostId,
        posts_post_id_models_type.PostId
      >(
        id: "lib/routes/posts/[postId]/server.dart#normalizePost",
        method: HttpMethod.post,
      );

  /// Builds a destination for this route.
  Destination to({
    required ({int postId}) params,
    posts_definition.Search? postsSearch,
    posts_post_id_definition.Search? search,
  }) {
    return _routeRoot
        .ref()
        .then(_routePosts.ref(search: postsSearch))
        .then(
          _routePostsPostId.ref(
            params: (postId: params.postId),
            search: search,
          ),
        )
        .destination;
  }
}
